<a href="https://colab.research.google.com/github/Ramandeep-Singh17/DLusingPyTorch/blob/main/9_1_optuna_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🚀 Optuna & Bayesian Optimization (Complete Master Notes)

---

# 🔥 1️⃣ Hyperparameter Tuning – Basic Idea

Machine Learning model me kuch parameters hote hain jo training se learn hote hain  
(jaise weights)

Aur kuch hote hain jo hum manually set karte hain  
Inhe bolte hain **Hyperparameters**

Example (Random Forest):

- n_estimators  
- max_depth  
- min_samples_split  

Goal:

👉 Best hyperparameter combination find karna  
👉 Accuracy maximize karna  

Mathematically:

f(x) = Accuracy  

Yaha:

x = hyperparameters  
f(x) = unknown function  

---

# 🔴 Traditional Methods

---

## 🔹 Grid Search

Sab possible combinations try karta hai.

Example:

max_depth = [1,2,3]  
n_estimators = [50,100]

Toh total combinations:

(1,50)  
(1,100)  
(2,50)  
(2,100)  
(3,50)  
(3,100)

Problem:

- Slow  
- Large search space me impossible  
- Previous trials ka knowledge use nahi karta  

👉 Pure brute force  

---

## 🔹 Random Search

Random combinations try karta hai.

100 combinations possible hain  
Sirf 20 randomly try karega

Problem:

- Fast  
- But memoryless  
- Previous trials ka data use nahi karta  

👉 Still dumb search  

---

# 🔥 Bayesian Optimization (Smart Search)

---

## 🔹 Basic Intuition

Maan lo humne try kiya:

max_depth = 2 → 80%  
max_depth = 4 → 88%  
max_depth = 6 → 84%  

Bayesian kya karega?

👉 In points ke beech relation samjhega  
👉 Ek probabilistic curve imagine karega  
👉 Estimate karega maximum kaha ho sakta hai  
👉 Us region me next trial karega  

Ye brute force nahi hai  
Ye intelligent prediction hai  

---

## 🔹 Core Idea

Real function unknown hoti hai  
Toh hum ek surrogate model banate hain:

P(f(x) | observed data)

Fir ek acquisition function decide karta hai:

👉 Next kaunsa hyperparameter try karna chahiye?

---

# 🚀 Optuna Framework

Optuna = Modern Bayesian Optimization Library

Works with:

- Sklearn  
- XGBoost  
- LightGBM  
- PyTorch  
- TensorFlow  
- ML + DL both  

---

# 🔹 Core Components

---

## 🔸 Study

Full experiment.

```python
study = optuna.create_study(direction="maximize")
```

Study = Collection of multiple trials  

---

## 🔸 Trial

Ek hyperparameter combination.

Example:

max_depth = 4  
n_estimators = 200  
accuracy = 0.88  

Har trial:

- Model train karta hai  
- Accuracy return karta hai  

---

## 🔥 Objective Function (Most Important)

```python
def objective(trial):

    max_depth = trial.suggest_int("max_depth", 1, 10)
    n_estimators = trial.suggest_int("n_estimators", 50, 300)

    model = RandomForestClassifier(
        max_depth=max_depth,
        n_estimators=n_estimators
    )

    model.fit(X_train, y_train)
    return model.score(X_test, y_test)
```

👉 Hyperparameters trial se aate hain  
👉 Accuracy return hoti hai  
👉 Optuna isi function ko optimize karta hai  

---

# 🔥 Sampler (Heart of Bayesian Search)

Sampler decide karta hai:

👉 Ab tak ke trials ke basis par next kya try karna chahiye?

Default:

TPESampler  

TPE kya karta hai?

- Good trials ka distribution banata hai  
- Bad trials ka distribution banata hai  
- Compare karta hai  
- Promising region me search karta hai  

---

# 🔄 Different Samplers

```python
optuna.samplers.TPESampler()
optuna.samplers.RandomSampler()
optuna.samplers.GridSampler()
optuna.samplers.CmaEsSampler()
```

Matlab:

Optuna me tum Grid aur Random search bhi chala sakte ho  

---

# 🔥 Define-by-Run (Dynamic Search Space)

Optuna ka sabse powerful feature.

Search space static nahi hota  
Trial ke andar dynamically define hota hai  

Example:

```python
def objective(trial):

    classifier = trial.suggest_categorical(
        "classifier", ["RF", "SVM"]
    )

    if classifier == "RF":

        n_estimators = trial.suggest_int("n_estimators", 50, 300)
        max_depth = trial.suggest_int("max_depth", 1, 10)

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth
        )

    else:

        C = trial.suggest_float("C", 0.01, 10.0)
        model = SVC(C=C)

    model.fit(X_train, y_train)
    return model.score(X_test, y_test)
```

Yaha:

👉 Algorithm bhi hyperparameter ban gaya  
👉 Optuna decide karega kaunsa best hai  

Isko bolte hain:

Dynamic Search Space  

---

# 🚀 Distributed & Fast

Optuna parallel trials run kar sakta hai.

- Multi-core CPU use karta hai  
- Distributed environment me run ho sakta hai  
- Large scale ML/DL tuning ke liye perfect  

Isliye industry me popular hai  

---

# 📊 Optuna Visualization

---

## 🔹 Optimization History

```python
plot_optimization_history(study)
```

Dikhata hai:

- X-axis = Trials  
- Y-axis = Accuracy  

Model improve ho raha hai ya nahi  

---

## 🔹 Parallel Coordinate Plot

```python
plot_parallel_coordinate(study)
```

Har trial ek line.

Dikhata hai:

- High accuracy kis range me mil rahi hai  
- Best hyperparameter combinations  

---

## 🔹 Slice Plot

```python
plot_slice(study)
```

Har hyperparameter ka individual effect.

Example:

max_depth vs accuracy  

---

## 🔹 Contour Plot

```python
plot_contour(study)
```

2 hyperparameters ke beech interaction.

Example:

max_depth vs n_estimators  
Color = Accuracy  

Best region visually detect hota hai  

---

## 🔹 Hyperparameter Importance

```python
plot_param_importances(study)
```

Batata hai:

Kaunsa hyperparameter sabse zyada impact kar raha hai  

Example:

max_depth → 60%  
n_estimators → 30%  

---

# 🌳 Random Forest Specific Understanding

Important hyperparameters:

- max_depth → overfitting control  
- n_estimators → stability  
- min_samples_split → tree complexity  
- max_features → randomness  

Importance graph se verify kar sakte ho  

---

# 🎯 Final Understanding

Grid → Exhaustive but slow  
Random → Fast but dumb  
Bayesian → Smart & Efficient  

Optuna powerful hai kyunki:

- Previous trials ka knowledge use karta hai  
- Dynamic search space allow karta hai  
- Algorithm selection possible hai  
- ML + DL compatible hai  
- Visualization support deta hai  
- Distributed execution possible hai  

---

# 🚀 Final Intuition

Hyperparameter tuning blindly guess karna nahi hai  

Ye ek optimization problem hai  

Aur Optuna usko intelligently solve karta hai.

In [36]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.7.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.47)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

# 🚀 Optuna – What, Why & Important Points (Short Notes)

---

# 🔥 Optuna Kya Hai?

Optuna ek **hyperparameter optimization framework** hai  
jo ML aur DL models ke liye best hyperparameters find karta hai.

👉 Ye mainly **Bayesian Optimization (TPE)** use karta hai  
👉 Smart search karta hai (random nahi)

---

# 🔥 Optuna Kyu Use Karte Hai?

✔️ Manual tuning time waste karta hai  
✔️ Grid search slow hota hai  
✔️ Random search dumb hota hai  

Optuna:

👉 Previous trials ka data use karta hai  
👉 Promising region me search karta hai  
👉 Faster convergence deta hai  
👉 Better results deta hai  

---

# 🔥 Optuna Kaha Use Hota Hai?

Works with:

- ✅ Scikit-Learn  
- ✅ XGBoost  
- ✅ LightGBM  
- ✅ PyTorch  
- ✅ TensorFlow  
- ✅ ML + DL both  

Industry me widely used hai 🚀  

---

# 🔥 Important Components (Very Important)

---

## 🔹 Study

Full experiment.

```python
study = optuna.create_study(direction="maximize")
```

👉 Study = Collection of trials  

---

## 🔹 Trial

Ek hyperparameter combination.

👉 Har trial model train karta hai  
👉 Ek score return karta hai  

---

## 🔥 Objective Function (Most Important)

```python
def objective(trial):
    ...
    return accuracy
```

👉 Hyperparameters suggest karta hai  
👉 Score return karta hai  
👉 Optuna isi ko optimize karta hai  

---

## 🔥 Sampler (Brain of Optuna)

Decide karta hai:

👉 Next kaunsa hyperparameter try karna chahiye?

Default:

TPESampler (Bayesian based)

---

## 🔥 Define-by-Run (Powerful Feature)

Dynamic search space allow karta hai.

👉 Trial ke andar search space define hota hai  
👉 Algorithm bhi hyperparameter ho sakta hai  

Ye Grid search me possible nahi hai  

---

# 🔥 Visualization Support

```python
plot_optimization_history(study)
plot_parallel_coordinate(study)
plot_slice(study)
plot_contour(study)
plot_param_importances(study)
```

👉 Model improvement track kar sakte ho  
👉 Hyperparameter impact samajh sakte ho  

---

# 🔥 Speed Advantage

✔️ Parallel trials run kar sakta hai  
✔️ Distributed compute support karta hai  
✔️ Large ML/DL tuning ke liye fast hai  

---

# 🎯 Final Summary (Interview Ready)

Optuna powerful hai kyunki:

👉 Bayesian Optimization use karta hai  
👉 Previous trials ka knowledge use karta hai  
👉 Dynamic search space allow karta hai  
👉 Visualization tools provide karta hai  
👉 ML + DL compatible hai  
👉 Fast & scalable hai  

---

# 🚀 One Line Definition

Optuna ek smart hyperparameter optimization framework hai  
jo Bayesian approach se efficiently best parameters find karta hai.

In [37]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [38]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [39]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [40]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [41]:
# Create a study object and optimize the objective function
#yaha accuracy liye hai isliye maximize agar loss lete tab minimize
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())
 # We aim to maximize accuracy TPE is by deauflt parameter
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-02-27 05:39:36,531] A new study created in memory with name: no-name-86e01314-0ea9-45c0-a193-22b4ef250a7f
[I 2026-02-27 05:39:38,184] Trial 0 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 163, 'max_depth': 9}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-02-27 05:39:39,083] Trial 1 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 121, 'max_depth': 16}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-02-27 05:39:40,124] Trial 2 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 111, 'max_depth': 9}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-02-27 05:39:42,217] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 20}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-02-27 05:39:42,811] Trial 4 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 57, 'max_depth': 19}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-02-27 05:39:43,531] Trial 5 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 19}. Best is trial 5 with value: 0.7783985102420857.
[I 2026-02-27 05:39:45,013] Trial 6 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 128, 'max_depth': 13}. Best is trial 5 with value: 0.7783985102420857.
[I 2026-02-27 05:39:46,842] Trial 7 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 120, 'max_depth': 11}. Best is trial 5 with value: 0.7783985102420857.
[I 2026-02-27 05:39:48,182] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 99, 'max_depth': 6}. Best is trial 5 with value: 0.7783985102420857.
[I 2026-02-27 05:39:50,834] Trial 9 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 123, 'max_depth': 18}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:39:53,195] Trial 10 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 200, 'max_depth': 3}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:39:53,705] Trial 11 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 52, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:39:54,674] Trial 12 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 82, 'max_depth': 17}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:39:55,601] Trial 13 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 80, 'max_depth': 14}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:39:57,385] Trial 14 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 151, 'max_depth': 18}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:39:58,225] Trial 15 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 77, 'max_depth': 20}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:00,324] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 149, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:04,039] Trial 17 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 191, 'max_depth': 12}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:06,007] Trial 18 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 138, 'max_depth': 18}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:07,159] Trial 19 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 94, 'max_depth': 10}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:08,232] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 70, 'max_depth': 14}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:09,710] Trial 21 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 110, 'max_depth': 17}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:10,805] Trial 22 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 97, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:12,172] Trial 23 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 132, 'max_depth': 19}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:13,418] Trial 24 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 114, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:16,559] Trial 25 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 177, 'max_depth': 18}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:18,265] Trial 26 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 137, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:19,036] Trial 27 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:19,393] Trial 28 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 65, 'max_depth': 17}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:19,899] Trial 29 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 103, 'max_depth': 7}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:20,376] Trial 30 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 87, 'max_depth': 13}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:21,018] Trial 31 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 124, 'max_depth': 12}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:21,706] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 130, 'max_depth': 14}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:22,585] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 167, 'max_depth': 19}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:23,165] Trial 34 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 110, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:23,793] Trial 35 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 120, 'max_depth': 13}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:24,587] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 154, 'max_depth': 10}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:25,317] Trial 37 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 19}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:26,116] Trial 38 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 160, 'max_depth': 8}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:26,920] Trial 39 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 180, 'max_depth': 3}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:27,531] Trial 40 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 17}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:28,361] Trial 41 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:29,299] Trial 42 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 115, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:30,254] Trial 43 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 129, 'max_depth': 18}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:30,960] Trial 44 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 124, 'max_depth': 20}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:31,440] Trial 45 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 89, 'max_depth': 13}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:32,183] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 143, 'max_depth': 15}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:32,535] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 66, 'max_depth': 19}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:33,089] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 104, 'max_depth': 17}. Best is trial 9 with value: 0.7802607076350093.
[I 2026-02-27 05:40:33,385] Trial 49 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 56, 'max_depth': 11}. Best is trial 9 with value: 0.7802607076350093.

In [42]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 123, 'max_depth': 18}

In [43]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Samplers in Optuna

In [44]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [45]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-02-27 05:40:33,663] A new study created in memory with name: no-name-9ac0e39a-b388-4d40-b163-4865cc632fc8
[I 2026-02-27 05:40:35,052] Trial 0 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 190, 'max_depth': 20}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-02-27 05:40:36,226] Trial 1 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 142, 'max_depth': 6}. Best is trial 0 with value: 0.7709497206703911.
[I 2026-02-27 05:40:37,612] Trial 2 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 132, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:39,402] Trial 3 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 152, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:43,174] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 198, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:44,813] Trial 5 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 117, 'max_depth': 8}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:45,967] Trial 6 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 95, 'max_depth': 5}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:48,255] Trial 7 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 188, 'max_depth': 11}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:50,257] Trial 8 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 172, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:51,479] Trial 9 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 127, 'max_depth': 4}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:52,991] Trial 10 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 132, 'max_depth': 16}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:55,876] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 160, 'max_depth': 5}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:57,495] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 189, 'max_depth': 15}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:58,030] Trial 13 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 105, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:58,309] Trial 14 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:58,981] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 133, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420856.
[I 2026-02-27 05:40:59,281] Trial 16 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 54, 'max_depth': 13}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:40:59,763] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:00,416] Trial 18 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 17}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:01,368] Trial 19 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 181, 'max_depth': 9}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:02,384] Trial 20 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 196, 'max_depth': 16}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:03,301] Trial 21 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 194, 'max_depth': 5}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:04,181] Trial 22 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 173, 'max_depth': 15}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:04,510] Trial 23 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 60, 'max_depth': 10}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:05,175] Trial 24 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 126, 'max_depth': 19}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:06,123] Trial 25 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 176, 'max_depth': 14}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:06,507] Trial 26 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 56, 'max_depth': 18}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:07,474] Trial 27 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 7}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:08,150] Trial 28 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 86, 'max_depth': 6}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:09,016] Trial 29 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 121, 'max_depth': 4}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:09,778] Trial 30 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 159, 'max_depth': 5}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:10,611] Trial 31 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 173, 'max_depth': 6}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:11,271] Trial 32 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 129, 'max_depth': 18}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:12,240] Trial 33 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 188, 'max_depth': 16}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:12,800] Trial 34 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 111, 'max_depth': 8}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:13,643] Trial 35 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 164, 'max_depth': 16}. Best is trial 16 with value: 0.7802607076350093.
[I 2026-02-27 05:41:14,051] Trial 36 finished with value: 0.7821229050279331 and parameters: {'n_estimators': 73, 'max_depth': 19}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:14,944] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 170, 'max_depth': 19}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:15,618] Trial 38 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 16}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:15,970] Trial 39 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 71, 'max_depth': 4}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:16,239] Trial 40 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 54, 'max_depth': 6}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:16,837] Trial 41 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 17}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:17,576] Trial 42 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 143, 'max_depth': 8}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:18,185] Trial 43 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 117, 'max_depth': 9}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:18,756] Trial 44 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 14}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:19,761] Trial 45 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 135, 'max_depth': 11}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:20,630] Trial 46 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 106, 'max_depth': 20}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:21,616] Trial 47 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 20}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:22,217] Trial 48 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 117, 'max_depth': 12}. Best is trial 36 with value: 0.7821229050279331.
[I 2026-02-27 05:41:22,484] Trial 49 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 51, 'max_depth': 12}. Best is trial 36 with value: 0.7821229050279331.

In [46]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279331
Best hyperparameters: {'n_estimators': 73, 'max_depth': 19}

In [47]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

In [48]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [49]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-02-27 05:41:22,659] A new study created in memory with name: no-name-f3be82d8-4e49-4df8-a676-441c33808714
[I 2026-02-27 05:41:23,161] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-02-27 05:41:23,929] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-02-27 05:41:24,206] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:24,742] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:25,264] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:25,524] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:26,237] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:26,992] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:27,767] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:28,795] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:29,827] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:30,880] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:32,063] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-02-27 05:41:32,456] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-02-27 05:41:33,252] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-02-27 05:41:33,684] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [50]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [51]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [52]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [53]:
# 1. Optimization History
plot_optimization_history(study).show()

In [54]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [55]:
# 3. Slice Plot
plot_slice(study).show()

In [56]:
# 4. Contour Plot
plot_contour(study).show()

In [57]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [58]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [59]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [60]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-02-27 05:41:34,211] A new study created in memory with name: no-name-3442ee10-d478-4695-90ba-7078e01770de
[I 2026-02-27 05:41:35,030] Trial 0 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 161, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-02-27 05:41:36,117] Trial 1 finished with value: 0.7597765363128492 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 192, 'learning_rate': 0.04681930295570701, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 8}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-02-27 05:41:36,149] Trial 2 finished with value: 0.7430167597765363 and parameters: {'classifier': 'SVM', 'C': 1.4369442418082472, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-02-27 05:41:36,308] Trial 3 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 44.519670316010235, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:36,379] Trial 4 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 15.635873905490685, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:38,308] Trial 5 finished with value: 0.7672253258845437 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 215, 'learning_rate': 0.014386027486760955, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 8}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:41,128] Trial 6 finished with value: 0.74487895716946 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 172, 'learning_rate': 0.010281799298987293, 'max_depth': 16, 'min_samples_split': 10, 'min_samples_leaf': 2}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:42,171] Trial 7 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 225, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:42,198] Trial 8 finished with value: 0.7616387337057727 and parameters: {'classifier': 'SVM', 'C': 0.18734212109464476, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:43,461] Trial 9 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 284, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:43,783] Trial 10 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 82.39533220581586, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:43,992] Trial 11 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 48.298546633885024, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:44,050] Trial 12 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 9.381329042412585, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:44,089] Trial 13 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 12.063839632986584, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:44,210] Trial 14 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 15.362831993257466, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:44,261] Trial 15 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.0321559617030887, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:44,321] Trial 16 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 32.00543344875523, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:44,369] Trial 17 finished with value: 0.7318435754189944 and parameters: {'classifier': 'SVM', 'C': 4.994613823021369, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:44,761] Trial 18 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 51, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:45,670] Trial 19 finished with value: 0.7486033519553073 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 51, 'learning_rate': 0.2918536125094064, 'max_depth': 12, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:45,713] Trial 20 finished with value: 0.6890130353817505 and parameters: {'classifier': 'SVM', 'C': 99.97795540461046, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:46,137] Trial 21 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 89.76874914115251, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:46,330] Trial 22 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 30.366252370764286, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:46,557] Trial 23 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 33.45648267915433, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:46,792] Trial 24 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 55.747618123825376, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:46,881] Trial 25 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 18.86011796665446, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:46,929] Trial 26 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.24325161269734, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:46,960] Trial 27 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 0.7429034564464391, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:48,795] Trial 28 finished with value: 0.7281191806331471 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 127, 'learning_rate': 0.25386085207235515, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 1}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:50,254] Trial 29 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 5, 'bootstrap': True}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:50,707] Trial 30 finished with value: 0.7765363128491619 and parameters: {'classifier': 'RandomForest', 'n_estimators': 110, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:50,870] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 54.54230837574215, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:51,037] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 45.24931440684562, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:51,144] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 21.262488308760382, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:51,412] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 77.19345163618335, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:58,166] Trial 35 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 251, 'learning_rate': 0.07187784927501166, 'max_depth': 14, 'min_samples_split': 6, 'min_samples_leaf': 5}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:58,322] Trial 36 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 45.70146633724552, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:41:58,426] Trial 37 finished with value: 0.6834264432029795 and parameters: {'classifier': 'SVM', 'C': 21.298822059823888, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:00,657] Trial 38 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 90, 'learning_rate': 0.038341056997538515, 'max_depth': 6, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:00,949] Trial 39 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 29.981969127968302, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:02,918] Trial 40 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 146, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:03,028] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.693784239143248, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:03,227] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 9.365029436319825, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:03,387] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.357656815850774, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:04,108] Trial 44 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 72.08726938005863, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:04,185] Trial 45 finished with value: 0.6983240223463687 and parameters: {'classifier': 'SVM', 'C': 12.252673583649186, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:04,702] Trial 46 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 43.89639387038377, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:04,791] Trial 47 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.9226618335635217, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:11,347] Trial 48 finished with value: 0.7299813780260708 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 260, 'learning_rate': 0.13178944651138771, 'max_depth': 13, 'min_samples_split': 8, 'min_samples_leaf': 9}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:11,793] Trial 49 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 24.518623215846564, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:12,741] Trial 50 finished with value: 0.7821229050279329 and parameters: {'classifier': 'RandomForest', 'n_estimators': 87, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:12,846] Trial 51 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 14.385296122772095, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:13,189] Trial 52 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 15.675436149368304, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:13,288] Trial 53 finished with value: 0.7113594040968342 and parameters: {'classifier': 'SVM', 'C': 0.13194470142691211, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:13,340] Trial 54 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.644615943362144, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:13,381] Trial 55 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.779226292578702, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:13,416] Trial 56 finished with value: 0.7597765363128492 and parameters: {'classifier': 'SVM', 'C': 12.568635679213873, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:13,655] Trial 57 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 67.67480539793702, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:13,683] Trial 58 finished with value: 0.6890130353817504 and parameters: {'classifier': 'SVM', 'C': 33.061769836288434, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:13,815] Trial 59 finished with value: 0.6741154562383613 and parameters: {'classifier': 'SVM', 'C': 98.31065804040884, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:16,060] Trial 60 finished with value: 0.7541899441340781 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 201, 'learning_rate': 0.02012270232048967, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:16,095] Trial 61 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.126280939773543, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:16,126] Trial 62 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 1.7793068053893417, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:16,162] Trial 63 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.261701730435799, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:16,186] Trial 64 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3914335295602341, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:17,220] Trial 65 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 244, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:17,382] Trial 66 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 37.71585740107508, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:17,424] Trial 67 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 4.721439174491867, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:17,452] Trial 68 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.121967485642535, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:17,482] Trial 69 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 2.2519387172436343, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:17,577] Trial 70 finished with value: 0.6852886405959032 and parameters: {'classifier': 'SVM', 'C': 57.73502306455967, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:17,827] Trial 71 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 77.07206141816114, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:18,201] Trial 72 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 89.96293353674649, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:18,394] Trial 73 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 56.30205392260789, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:18,499] Trial 74 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 28.288160117719745, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:19,729] Trial 75 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 78, 'learning_rate': 0.10222897465103971, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:20,340] Trial 76 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 137, 'max_depth': 3, 'min_samples_split': 4, 'min_samples_leaf': 9, 'bootstrap': True}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:20,434] Trial 77 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 18.80656648785572, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:20,472] Trial 78 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 39.24604736062092, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:20,499] Trial 79 finished with value: 0.6983240223463687 and parameters: {'classifier': 'SVM', 'C': 10.033637961284567, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:20,545] Trial 80 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 6.835341613235031, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.
[I 2026-02-27 05:42:20,682] Trial 81 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 24.479592143960012, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 3 with value: 0.7858472998137801.

In [61]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 44.519670316010235, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7858472998137801

In [62]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.763501,2026-02-27 05:41:34.214431,2026-02-27 05:41:35.030759,0 days 00:00:00.816328,NaN,True,RandomForest,NaN,NaN,NaN,10.0,3.0,4.0,161.0,COMPLETE
1,1,0.759777,2026-02-27 05:41:35.031636,2026-02-27 05:41:36.117387,0 days 00:00:01.085751,NaN,NaN,GradientBoosting,NaN,NaN,0.046819,4.0,8.0,3.0,192.0,COMPLETE
2,2,0.743017,2026-02-27 05:41:36.118391,2026-02-27 05:41:36.149344,0 days 00:00:00.030953,1.436944,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
3,3,0.785847,2026-02-27 05:41:36.150850,2026-02-27 05:41:36.308002,0 days 00:00:00.157152,44.519670,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.785847,2026-02-27 05:41:36.308921,2026-02-27 05:41:36.379334,0 days 00:00:00.070413,15.635874,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.735568,2026-02-27 05:42:28.644207,2026-02-27 05:42:28.681682,0 days 00:00:00.037475,31.482327,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.694600,2026-02-27 05:42:28.682571,2026-02-27 05:42:28.714143,0 days 00:00:00.031572,47.622297,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.672253,2026-02-27 05:42:28.714931,2026-02-27 05:42:28.851454,0 days 00:00:00.136523,96.619728,NaN,SVM,auto,poly,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.785847,2026-02-27 05:42:28.852824,2026-02-27 05:42:29.132217,0 days 00:00:00.279393,62.972421,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
99,99,0.785847,2026-02-27 05:42:29.133145,2026-02-27 05:42:29.177260,0 days 00:00:00.044115,5.936542,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [63]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 78
RandomForest        11
GradientBoosting    11
Name: count, dtype: int64

In [64]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.746403
RandomForest        0.767564
SVM                 0.766963
Name: value, dtype: float64

In [65]:
# 1. Optimization History
plot_optimization_history(study).show()

In [66]:
# 3. Slice Plot
plot_slice(study).show()

In [70]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

[W 2026-02-27 06:05:26,516] Study instance does not contain completed trials.

In [71]:
! pip install optuna-integration[xgboost]
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.7.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.7.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.2.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.47)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.27.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.3)
Downloading optuna_integration-4.7.0-py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 kB 4.6 MB/s eta 0:00:00
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.7.0

[I 2026-02-27 06:06:46,186] A new study created in memory with name: no-name-c7fcae6d-70c8-4883-ae71-bf5997ba4556

[0]	train-mlogloss:1.07782	eval-mlogloss:1.08116
[1]	train-mlogloss:1.02694	eval-mlogloss:1.02797
[2]	train-mlogloss:0.97959	eval-mlogloss:0.97892
[3]	train-mlogloss:0.94588	eval-mlogloss:0.94190
[4]	train-mlogloss:0.91082	eval-mlogloss:0.90406
[5]	train-mlogloss:0.87074	eval-mlogloss:0.86214
[6]	train-mlogloss:0.84206	eval-mlogloss:0.83388
[7]	train-mlogloss:0.82053	eval-mlogloss:0.81342
[8]	train-mlogloss:0.78602	eval-mlogloss:0.77720
[9]	train-mlogloss:0.76143	eval-mlogloss:0.75298
[10]	train-mlogloss:0.73047	eval-mlogloss:0.72131
[11]	train-mlogloss:0.70490	eval-mlogloss:0.69485
[12]	train-mlogloss:0.69512	eval-mlogloss:0.68396
[13]	train-mlogloss:0.66799	eval-mlogloss:0.65430
[14]	train-mlogloss:0.65936	eval-mlogloss:0.64652
[15]	train-mlogloss:0.64490	eval-mlogloss:0.63208
[16]	train-mlogloss:0.62973	eval-mlogloss:0.61721
[17]	train-mlogloss:0.61215	eval-mlogloss:0.59989
[18]	train-mlogloss:0.59955	eval-mlogloss:0.58727
[19]	train-mlogloss:0.58745	eval-mlogloss:0.57517
[20]	train-mlogloss:0.56611	eval-mlogloss:0.55206
[21]	train-mlogloss:0.55180	eval-mlogloss:0.53710
[22]	train-mlogloss:0.53992	eval-mlogloss:0.52544
[23]	train-mlogloss:0.52106	eval-mlogloss:0.50523
[24]	train-mlogloss:0.51145	eval-mlogloss:0.49492
[25]	train-mlogloss:0.49871	eval-mlogloss:0.48028
[26]	train-mlogloss:0.48555	eval-mlogloss:0.46595
[27]	train-mlogloss:0.48264	eval-mlogloss:0.46337
[28]	train-mlogloss:0.47798	eval-mlogloss:0.45950
[29]	train-mlogloss:0.46533	eval-mlogloss:0.44472
[30]	train-mlogloss:0.45431	eval-mlogloss:0.43251
[31]	train-mlogloss:0.45158	eval-mlogloss:0.43108
[32]	train-mlogloss:0.44488	eval-mlogloss:0.42425
[33]	train-mlogloss:0.43968	eval-mlogloss:0.41893
[34]	train-mlogloss:0.42784	eval-mlogloss:0.40634
[35]	train-mlogloss:0.42143	eval-mlogloss:0.39869
[36]	train-mlogloss:0.41624	eval-mlogloss:0.39352
[37]	train-mlogloss:0.40751	eval-mlogloss:0.38449
[38]	train-mlogloss:0.39779	eval-mlogloss:0.37385
[39]	train-mlogloss:0.39176	eval-mlogloss:0.36716
[40]	train-mlogloss:0.38887	eval-mlogloss:0.36455
[41]	train-mlogloss:0.38081	eval-mlogloss:0.35513
[42]	train-mlogloss:0.37929	eval-mlogloss:0.35428
[43]	train-mlogloss:0.37252	eval-mlogloss:0.34670
[44]	train-mlogloss:0.36461	eval-mlogloss:0.33761
[45]	train-mlogloss:0.36122	eval-mlogloss:0.33387
[46]	train-mlogloss:0.35396	eval-mlogloss:0.32551
[47]	train-mlogloss:0.34952	eval-mlogloss:0.32075
[48]	train-mlogloss:0.34300	eval-mlogloss:0.31335
[49]	train-mlogloss:0.33639	eval-mlogloss:0.30602
[50]	train-mlogloss:0.33024	eval-mlogloss:0.29841
[51]	train-mlogloss:0.32719	eval-mlogloss:0.29501
[52]	train-mlogloss:0.32404	eval-mlogloss:0.29183
[53]	train-mlogloss:0.31637	eval-mlogloss:0.28244
[54]	train-mlogloss:0.31366	eval-mlogloss:0.27932
[55]	train-mlogloss:0.30635	eval-mlogloss:0.27144
[56]	train-mlogloss:0.30135	eval-mlogloss:0.26569
[57]	train-mlogloss:0.29462	eval-mlogloss:0.25737
[58]	train-mlogloss:0.29154	eval-mlogloss:0.25445
[59]	train-mlogloss:0.28990	eval-mlogloss:0.25294
[60]	train-mlogloss:0.28528	eval-mlogloss:0.24753
[61]	train-mlogloss:0.28179	eval-mlogloss:0.24317
[62]	train-mlogloss:0.27565	eval-mlogloss:0.23650
[63]	train-mlogloss:0.27289	eval-mlogloss:0.23366
[64]	train-mlogloss:0.27171	eval-mlogloss:0.23234
[65]	train-mlogloss:0.26904	eval-mlogloss:0.22934
[66]	train-mlogloss:0.26539	eval-mlogloss:0.22523
[67]	train-mlogloss:0.26252	eval-mlogloss:0.22210
[68]	train-mlogloss:0.26166	eval-mlogloss:0.22111
[69]	train-mlogloss:0.25670	eval-mlogloss:0.21544
[70]	train-mlogloss:0.25485	eval-mlogloss:0.21298
[71]	train-mlogloss:0.25031	eval-mlogloss:0.20736
[72]	train-mlogloss:0.24723	eval-mlogloss:0.20383
[73]	train-mlogloss:0.24557	eval-mlogloss:0.20187
[74]	train-mlogloss:0.24304	eval-mlogloss:0.19926
[75]	train-mlogloss:0.23980	eval-mlogloss:0.19510
[76]	train-mlogloss:0.23795	eval-mlogloss:0.19324
[77]	train-mlogloss:0.23613	eval-mlogloss:0.19152
[78]	train-mlogloss:0.23490	eval-mlogloss:0.19044
[79]	train-mlogloss:0.23314	eval-mlogloss:0.18880
[80]	train-mlogloss:0.23142	eval-mlogloss:0.18693
[81]	train-mlogloss:0.22936	eval-mlogloss:0.18454
[82]	train-mlogloss:0.22853	eval-mlogloss:0.18353
[83]	train-mlogloss:0.22688	eval-mlogloss:0.18145
[84]	train-mlogloss:0.22559	eval-mlogloss:0.18016
[85]	train-mlogloss:0.22429	eval-mlogloss:0.17836
[86]	train-mlogloss:0.22261	eval-mlogloss:0.17610
[87]	train-mlogloss:0.22087	eval-mlogloss:0.17408
[88]	train-mlogloss:0.21884	eval-mlogloss:0.17146
[89]	train-mlogloss:0.21691	eval-mlogloss:0.16922
[90]	train-mlogloss:0.21562	eval-mlogloss:0.16744
[91]	train-mlogloss:0.21517	eval-mlogloss:0.16680
[92]	train-mlogloss:0.21365	eval-mlogloss:0.16502
[93]	train-mlogloss:0.21345	eval-mlogloss:0.16465
[94]	train-mlogloss:0.21196	eval-mlogloss:0.16261
[95]	train-mlogloss:0.21080	eval-mlogloss:0.16100
[96]	train-mlogloss:0.20974	eval-mlogloss:0.15982
[97]	train-mlogloss:0.20880	eval-mlogloss:0.15849
[98]	train-mlogloss:0.20779	eval-mlogloss:0.15708
[99]	train-mlogloss:0.20764	eval-mlogloss:0.15709
[100]	train-mlogloss:0.20735	eval-mlogloss:0.15698
[101]	train-mlogloss:0.20638	eval-mlogloss:0.15562
[102]	train-mlogloss:0.20611	eval-mlogloss:0.15556
[103]	train-mlogloss:0.20511	eval-mlogloss:0.15445
[104]	train-mlogloss:0.20484	eval-mlogloss:0.15413
[105]	train-mlogloss:0.20465	eval-mlogloss:0.15386
[106]	train-mlogloss:0.20431	eval-mlogloss:0.15333
[107]	train-mlogloss:0.20348	eval-mlogloss:0.15214
[108]	train-mlogloss:0.20328	eval-mlogloss:0.15180
[109]	train-mlogloss:0.20237	eval-mlogloss:0.15050
[110]	train-mlogloss:0.20165	eval-mlogloss:0.14947
[111]	train-mlogloss:0.20157	eval-mlogloss:0.14932
[112]	train-mlogloss:0.20138	eval-mlogloss:0.14933
[113]	train-mlogloss:0.20056	eval-mlogloss:0.14815
[114]	train-mlogloss:0.20045	eval-mlogloss:0.14796
[115]	train-mlogloss:0.20029	eval-mlogloss:0.14803
[116]	train-mlogloss:0.19948	eval-mlogloss:0.14697
[117]	train-mlogloss:0.19939	eval-mlogloss:0.14681
[118]	train-mlogloss:0.19870	eval-mlogloss:0.14586
[119]	train-mlogloss:0.19859	eval-mlogloss:0.14594
[120]	train-mlogloss:0.19781	eval-mlogloss:0.14484
[121]	train-mlogloss:0.19761	eval-mlogloss:0.14458
[122]	train-mlogloss:0.19674	eval-mlogloss:0.14329
[123]	train-mlogloss:0.19601	eval-mlogloss:0.14224
[124]	train-mlogloss:0.19590	eval-mlogloss:0.14232
[125]	train-mlogloss:0.19530	eval-mlogloss:0.14152
[126]	train-mlogloss:0.19523	eval-mlogloss:0.14140
[127]	train-mlogloss:0.19510	eval-mlogloss:0.14120
[128]	train-mlogloss:0.19437	eval-mlogloss:0.14010
[129]	train-mlogloss:0.19376	eval-mlogloss:0.13921
[130]	train-mlogloss:0.19373	eval-mlogloss:0.13926
[131]	train-mlogloss:0.19370	eval-mlogloss:0.13922
[132]	train-mlogloss:0.19362	eval-mlogloss:0.13910
[133]	train-mlogloss:0.19356	eval-mlogloss:0.13899
[134]	train-mlogloss:0.19352	eval-mlogloss:0.13905
[135]	train-mlogloss:0.19282	eval-mlogloss:0.13799
[136]	train-mlogloss:0.19272	eval-mlogloss:0.13781
[137]	train-mlogloss:0.19194	eval-mlogloss:0.13675
[138]	train-mlogloss:0.19146	eval-mlogloss:0.13606
[139]	train-mlogloss:0.19134	eval-mlogloss:0.13605
[140]	train-mlogloss:0.19123	eval-mlogloss:0.13589
[141]	train-mlogloss:0.19051	eval-mlogloss:0.13488
[142]	train-mlogloss:0.19036	eval-mlogloss:0.13470
[143]	train-mlogloss:0.18971	eval-mlogloss:0.13380
[144]	train-mlogloss:0.18925	eval-mlogloss:0.13319
[145]	train-mlogloss:0.18917	eval-mlogloss:0.13305
[146]	train-mlogloss:0.18913	eval-mlogloss:0.13298
[147]	train-mlogloss:0.18907	eval-mlogloss:0.13305
[148]	train-mlogloss:0.18903	eval-mlogloss:0.13299
[149]	train-mlogloss:0.18890	eval-mlogloss:0.13280
[150]	train-mlogloss:0.18830	eval-mlogloss:0.13192
[151]	train-mlogloss:0.18791	eval-mlogloss:0.13136
[152]	train-mlogloss:0.18777	eval-mlogloss:0.13119
[153]	train-mlogloss:0.18775	eval-mlogloss:0.13115
[154]	train-mlogloss:0.18715	eval-mlogloss:0.13031
[155]	train-mlogloss:0.18709	eval-mlogloss:0.13022
[156]	train-mlogloss:0.18704	eval-mlogloss:0.13013
[157]	train-mlogloss:0.18686	eval-mlogloss:0.12992
[158]	train-mlogloss:0.18686	eval-mlogloss:0.12992
[159]	train-mlogloss:0.18637	eval-mlogloss:0.12924
[160]	train-mlogloss:0.18595	eval-mlogloss:0.12861
[161]	train-mlogloss:0.18595	eval-mlogloss:0.12861
[162]	train-mlogloss:0.18591	eval-mlogloss:0.12855
[163]	train-mlogloss:0.18591	eval-mlogloss:0.12855
[164]	train-mlogloss:0.18588	eval-mlogloss:0.12850
[165]	train-mlogloss:0.18545	eval-mlogloss:0.12787
[166]	train-mlogloss:0.18499	eval-mlogloss:0.12720
[167]	train-mlogloss:0.18499	eval-mlogloss:0.12720
[168]	train-mlogloss:0.18456	eval-mlogloss:0.12657
[169]	train-mlogloss:0.18446	eval-mlogloss:0.12647
[170]	train-mlogloss:0.18426	eval-mlogloss:0.12646
[171]	train-mlogloss:0.18414	eval-mlogloss:0.12649
[172]	train-mlogloss:0.18414	eval-mlogloss:0.12649
[173]	train-mlogloss:0.18408	eval-mlogloss:0.12657
[174]	train-mlogloss:0.18408	eval-mlogloss:0.12657
[175]	train-mlogloss:0.18396	eval-mlogloss:0.12662
[176]	train-mlogloss:0.18396	eval-mlogloss:0.12662
[177]	train-mlogloss:0.18396	eval-mlogloss:0.12662
[178]	train-mlogloss:0.18390	eval-mlogloss:0.12655
[179]	train-mlogloss:0.18390	eval-mlogloss:0.12655
[180]	train-mlogloss:0.18390	eval-mlogloss:0.12655
[181]	train-mlogloss:0.18387	eval-mlogloss:0.12650
[182]	train-mlogloss:0.18380	eval-mlogloss:0.12643
[183]	train-mlogloss:0.18374	eval-mlogloss:0.12634
[184]	train-mlogloss:0.18374	eval-mlogloss:0.12634
[185]	train-mlogloss:0.18374	eval-mlogloss:0.12634
[186]	train-mlogloss:0.18368	eval-mlogloss:0.12628
[187]	train-mlogloss:0.18356	eval-mlogloss:0.12612
[188]	train-mlogloss:0.18321	eval-mlogloss:0.12559
[189]	train-mlogloss:0.18316	eval-mlogloss:0.12556
[190]	train-mlogloss:0.18314	eval-mlogloss:0.12558
[191]	train-mlogloss:0.18307	eval-mlogloss:0.12547
[192]	train-mlogloss:0.18307	eval-mlogloss:0.12547
[193]	train-mlogloss:0.18299	eval-mlogloss:0.12538
[194]	train-mlogloss:0.18266	eval-mlogloss:0.12488
[195]	train-mlogloss:0.18266	eval-mlogloss:0.12488
[196]	train-mlogloss:0.18263	eval-mlogloss:0.12485
[197]	train-mlogloss:0.18262	eval-mlogloss:0.12485
[198]	train-mlogloss:0.18255	eval-mlogloss:0.12479
[199]	train-mlogloss:0.18248	eval-mlogloss:0.12487
[200]	train-mlogloss:0.18246	eval-mlogloss:0.12482
[201]	train-mlogloss:0.18246	eval-mlogloss:0.12482
[202]	train-mlogloss:0.18242	eval-mlogloss:0.12479
[203]	train-mlogloss:0.18242	eval-mlogloss:0.12479
[204]	train-mlogloss:0.18235	eval-mlogloss:0.12472
[205]	train-mlogloss:0.18235	eval-mlogloss:0.12472
[206]	train-mlogloss:0.18230	eval-mlogloss:0.12467
[207]	train-mlogloss:0.18188	eval-mlogloss:0.12409
[208]	train-mlogloss:0.18188	eval-mlogloss:0.12409
[209]	train-mlogloss:0.18157	eval-mlogloss:0.12361
[210]	train-mlogloss:0.18157	eval-mlogloss:0.12362
[211]	train-mlogloss:0.18151	eval-mlogloss:0.12368
[212]	train-mlogloss:0.18144	eval-mlogloss:0.12362
[213]	train-mlogloss:0.18141	eval-mlogloss:0.12359
[214]	train-mlogloss:0.18141	eval-mlogloss:0.12359
[215]	train-mlogloss:0.18111	eval-mlogloss:0.12311
[216]	train-mlogloss:0.18105	eval-mlogloss:0.12318
[217]	train-mlogloss:0.18105	eval-mlogloss:0.12318
[218]	train-mlogloss:0.18094	eval-mlogloss:0.12319
[219]	train-mlogloss:0.18092	eval-mlogloss:0.12319
[220]	train-mlogloss:0.18086	eval-mlogloss:0.12312
[221]	train-mlogloss:0.18079	eval-mlogloss:0.12304
[222]	train-mlogloss:0.18079	eval-mlogloss:0.12304
[223]	train-mlogloss:0.18079	eval-mlogloss:0.12304
[224]	train-mlogloss:0.18079	eval-mlogloss:0.12304
[225]	train-mlogloss:0.18073	eval-mlogloss:0.12299
[226]	train-mlogloss:0.18073	eval-mlogloss:0.12299
[227]	train-mlogloss:0.18073	eval-mlogloss:0.12299
[228]	train-mlogloss:0.18070	eval-mlogloss:0.12295
[229]	train-mlogloss:0.18062	eval-mlogloss:0.12287
[230]	train-mlogloss:0.18058	eval-mlogloss:0.12281
[231]	train-mlogloss:0.18058	eval-mlogloss:0.12281
[232]	train-mlogloss:0.18055	eval-mlogloss:0.12276
[233]	train-mlogloss:0.18047	eval-mlogloss:0.12270
[234]	train-mlogloss:0.18047	eval-mlogloss:0.12270
[235]	train-mlogloss:0.18047	eval-mlogloss:0.12271
[236]	train-mlogloss:0.18047	eval-mlogloss:0.12271
[237]	train-mlogloss:0.18044	eval-mlogloss:0.12272
[238]	train-mlogloss:0.18044	eval-mlogloss:0.12272
[239]	train-mlogloss:0.18039	eval-mlogloss:0.12278
[240]	train-mlogloss:0.18010	eval-mlogloss:0.12233
[241]	train-mlogloss:0.18007	eval-mlogloss:0.12231
[242]	train-mlogloss:0.18007	eval-mlogloss:0.12231
[243]	train-mlogloss:0.18004	eval-mlogloss:0.12231
[244]	train-mlogloss:0.18004	eval-mlogloss:0.12231
[245]	train-mlogloss:0.18001	eval-mlogloss:0.12225
[246]	train-mlogloss:0.18001	eval-mlogloss:0.12225
[247]	train-mlogloss:0.17997	eval-mlogloss:0.12223
[248]	train-mlogloss:0.17991	eval-mlogloss:0.12216
[249]	train-mlogloss:0.17960	eval-mlogloss:0.12168
[250]	train-mlogloss:0.17924	eval-mlogloss:0.12117
[251]	train-mlogloss:0.17920	eval-mlogloss:0.12112
[252]	train-mlogloss:0.17920	eval-mlogloss:0.12112
[253]	train-mlogloss:0.17917	eval-mlogloss:0.12109
[254]	train-mlogloss:0.17917	eval-mlogloss:0.12109
[255]	train-mlogloss:0.17917	eval-mlogloss:0.12109
[256]	train-mlogloss:0.17913	eval-mlogloss:0.12103
[257]	train-mlogloss:0.17913	eval-mlogloss:0.12103
[258]	train-mlogloss:0.17909	eval-mlogloss:0.12098
[259]	train-mlogloss:0.17909	eval-mlogloss:0.12098
[260]	train-mlogloss:0.17909	eval-mlogloss:0.12098
[261]	train-mlogloss:0.17909	eval-mlogloss:0.12098
[262]	train-mlogloss:0.17908	eval-mlogloss:0.12096
[263]	train-mlogloss:0.17908	eval-mlogloss:0.12096
[264]	train-mlogloss:0.17903	eval-mlogloss:0.12091
[265]	train-mlogloss:0.17896	eval-mlogloss:0.12081
[266]	train-mlogloss:0.17896	eval-mlogloss:0.12081
[267]	train-mlogloss:0.17892	eval-mlogloss:0.12076
[268]	train-mlogloss:0.17886	eval-mlogloss:0.12072
[269]	train-mlogloss:0.17886	eval-mlogloss:0.12072
[270]	train-mlogloss:0.17884	eval-mlogloss:0.12068
[271]	train-mlogloss:0.17879	eval-mlogloss:0.12075
[272]	train-mlogloss:0.17879	eval-mlogloss:0.12075
[273]	train-mlogloss:0.17874	eval-mlogloss:0.12068
[274]	train-mlogloss:0.17874	eval-mlogloss:0.12068
[275]	train-mlogloss:0.17874	eval-mlogloss:0.12068
[276]	train-mlogloss:0.17874	eval-mlogloss:0.12068
[277]	train-mlogloss:0.17874	eval-mlogloss:0.12068
[278]	train-mlogloss:0.17874	eval-mlogloss:0.12068
[279]	train-mlogloss:0.17871	eval-mlogloss:0.12065
[280]	train-mlogloss:0.17871	eval-mlogloss:0.12065
[281]	train-mlogloss:0.17871	eval-mlogloss:0.12065
[282]	train-mlogloss:0.17871	eval-mlogloss:0.12065
[283]	train-mlogloss:0.17871	eval-mlogloss:0.12065
[284]	train-mlogloss:0.17871	eval-mlogloss:0.12065
[285]	train-mlogloss:0.17871	eval-mlogloss:0.12065
[286]	train-mlogloss:0.17866	eval-mlogloss:0.12061
[287]	train-mlogloss:0.17839	eval-mlogloss:0.12017
[288]	train-mlogloss:0.17832	eval-mlogloss:0.12010
[289]	train-mlogloss:0.17832	eval-mlogloss:0.12010
[290]	train-mlogloss:0.17829	eval-mlogloss:0.12007
[291]	train-mlogloss:0.17829	eval-mlogloss:0.12007
[292]	train-mlogloss:0.17826	eval-mlogloss:0.12004
[293]	train-mlogloss:0.17821	eval-mlogloss:0.12010
[294]	train-mlogloss:0.17821	eval-mlogloss:0.12010
[295]	train-mlogloss:0.17817	eval-mlogloss:0.12007
[296]	train-mlogloss:0.17810	eval-mlogloss:0.12001
[297]	train-mlogloss:0.17810	eval-mlogloss:0.12001
[298]	train-mlogloss:0.17810	eval-mlogloss:0.12001
[299]	train-mlogloss:0.17810	eval-mlogloss:0.12001

[I 2026-02-27 06:06:46,862] Trial 0 finished with value: 1.0 and parameters: {'lambda': 0.39807941021872445, 'alpha': 0.7194273512369619, 'eta': 0.04346150465161059, 'gamma': 0.018493726865413496, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.9565429480675249, 'colsample_bytree': 0.4240353787786787}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.84740	eval-mlogloss:0.86480
[1]	train-mlogloss:0.63316	eval-mlogloss:0.65531
[2]	train-mlogloss:0.48463	eval-mlogloss:0.49476
[3]	train-mlogloss:0.38133	eval-mlogloss:0.38772
[4]	train-mlogloss:0.30345	eval-mlogloss:0.30740
[5]	train-mlogloss:0.24391	eval-mlogloss:0.23719
[6]	train-mlogloss:0.19750	eval-mlogloss:0.20382
[7]	train-mlogloss:0.16460	eval-mlogloss:0.16747
[8]	train-mlogloss:0.13949	eval-mlogloss:0.13436
[9]	train-mlogloss:0.11841	eval-mlogloss:0.11236
[10]	train-mlogloss:0.10164	eval-mlogloss:0.09808
[11]	train-mlogloss:0.08760	eval-mlogloss:0.08464
[12]	train-mlogloss:0.08226	eval-mlogloss:0.08277
[13]	train-mlogloss:0.07254	eval-mlogloss:0.07176
[14]	train-mlogloss:0.06804	eval-mlogloss:0.06592
[15]	train-mlogloss:0.06285	eval-mlogloss:0.05721
[16]	train-mlogloss:0.05960	eval-mlogloss:0.05021
[17]	train-mlogloss:0.05580	eval-mlogloss:0.04558
[18]	train-mlogloss:0.05254	eval-mlogloss:0.04379
[19]	train-mlogloss:0.05121	eval-mlogloss:0.04351
[20]	train-mlogloss:0.04973	eval-mlogloss:0.04052
[21]	train-mlogloss:0.04759	eval-mlogloss:0.03426
[22]	train-mlogloss:0.04660	eval-mlogloss:0.03166
[23]	train-mlogloss:0.04513	eval-mlogloss:0.02939
[24]	train-mlogloss:0.04384	eval-mlogloss:0.03052
[25]	train-mlogloss:0.04217	eval-mlogloss:0.03046
[26]	train-mlogloss:0.04104	eval-mlogloss:0.03106
[27]	train-mlogloss:0.04029	eval-mlogloss:0.03173
[28]	train-mlogloss:0.03886	eval-mlogloss:0.03247
[29]	train-mlogloss:0.03815	eval-mlogloss:0.03098
[30]	train-mlogloss:0.03732	eval-mlogloss:0.03137
[31]	train-mlogloss:0.03701	eval-mlogloss:0.03043
[32]	train-mlogloss:0.03582	eval-mlogloss:0.02900
[33]	train-mlogloss:0.03537	eval-mlogloss:0.02948
[34]	train-mlogloss:0.03481	eval-mlogloss:0.02880
[35]	train-mlogloss:0.03410	eval-mlogloss:0.02691
[36]	train-mlogloss:0.03345	eval-mlogloss:0.02704
[37]	train-mlogloss:0.03324	eval-mlogloss:0.02692
[38]	train-mlogloss:0.03269	eval-mlogloss:0.02794
[39]	train-mlogloss:0.03227	eval-mlogloss:0.02729
[40]	train-mlogloss:0.03184	eval-mlogloss:0.02702
[41]	train-mlogloss:0.03160	eval-mlogloss:0.02736
[42]	train-mlogloss:0.03111	eval-mlogloss:0.02534
[43]	train-mlogloss:0.03087	eval-mlogloss:0.02534
[44]	train-mlogloss:0.03051	eval-mlogloss:0.02406
[45]	train-mlogloss:0.03029	eval-mlogloss:0.02383
[46]	train-mlogloss:0.03032	eval-mlogloss:0.02465
[47]	train-mlogloss:0.02987	eval-mlogloss:0.02429
[48]	train-mlogloss:0.02965	eval-mlogloss:0.02490
[49]	train-mlogloss:0.02956	eval-mlogloss:0.02468
[50]	train-mlogloss:0.02922	eval-mlogloss:0.02376
[51]	train-mlogloss:0.02888	eval-mlogloss:0.02261
[52]	train-mlogloss:0.02874	eval-mlogloss:0.02374
[53]	train-mlogloss:0.02855	eval-mlogloss:0.02331
[54]	train-mlogloss:0.02847	eval-mlogloss:0.02345
[55]	train-mlogloss:0.02793	eval-mlogloss:0.02215
[56]	train-mlogloss:0.02779	eval-mlogloss:0.02238
[57]	train-mlogloss:0.02778	eval-mlogloss:0.02193
[58]	train-mlogloss:0.02768	eval-mlogloss:0.02075
[59]	train-mlogloss:0.02730	eval-mlogloss:0.02202
[60]	train-mlogloss:0.02703	eval-mlogloss:0.02195
[61]	train-mlogloss:0.02682	eval-mlogloss:0.02113
[62]	train-mlogloss:0.02673	eval-mlogloss:0.02162
[63]	train-mlogloss:0.02636	eval-mlogloss:0.02020
[64]	train-mlogloss:0.02605	eval-mlogloss:0.02015
[65]	train-mlogloss:0.02592	eval-mlogloss:0.01984
[66]	train-mlogloss:0.02584	eval-mlogloss:0.02013
[67]	train-mlogloss:0.02555	eval-mlogloss:0.01924
[68]	train-mlogloss:0.02533	eval-mlogloss:0.01937
[69]	train-mlogloss:0.02515	eval-mlogloss:0.01896
[70]	train-mlogloss:0.02517	eval-mlogloss:0.01831
[71]	train-mlogloss:0.02505	eval-mlogloss:0.01679
[72]	train-mlogloss:0.02502	eval-mlogloss:0.01712
[73]	train-mlogloss:0.02495	eval-mlogloss:0.01761
[74]	train-mlogloss:0.02487	eval-mlogloss:0.01771
[75]	train-mlogloss:0.02486	eval-mlogloss:0.01766
[76]	train-mlogloss:0.02484	eval-mlogloss:0.01784
[77]	train-mlogloss:0.02473	eval-mlogloss:0.01825
[78]	train-mlogloss:0.02473	eval-mlogloss:0.01844
[79]	train-mlogloss:0.02443	eval-mlogloss:0.01805
[80]	train-mlogloss:0.02427	eval-mlogloss:0.01775
[81]	train-mlogloss:0.02396	eval-mlogloss:0.01682
[82]	train-mlogloss:0.02393	eval-mlogloss:0.01722
[83]	train-mlogloss:0.02386	eval-mlogloss:0.01741
[84]	train-mlogloss:0.02358	eval-mlogloss:0.01736
[85]	train-mlogloss:0.02344	eval-mlogloss:0.01674
[86]	train-mlogloss:0.02346	eval-mlogloss:0.01714
[87]	train-mlogloss:0.02332	eval-mlogloss:0.01719
[88]	train-mlogloss:0.02326	eval-mlogloss:0.01706
[89]	train-mlogloss:0.02314	eval-mlogloss:0.01687
[90]	train-mlogloss:0.02303	eval-mlogloss:0.01710
[91]	train-mlogloss:0.02308	eval-mlogloss:0.01760
[92]	train-mlogloss:0.02295	eval-mlogloss:0.01713
[93]	train-mlogloss:0.02294	eval-mlogloss:0.01743
[94]	train-mlogloss:0.02297	eval-mlogloss:0.01763
[95]	train-mlogloss:0.02317	eval-mlogloss:0.01709
[96]	train-mlogloss:0.02330	eval-mlogloss:0.01780
[97]	train-mlogloss:0.02310	eval-mlogloss:0.01813
[98]	train-mlogloss:0.02300	eval-mlogloss:0.01776
[99]	train-mlogloss:0.02292	eval-mlogloss:0.01801
[100]	train-mlogloss:0.02266	eval-mlogloss:0.01769
[101]	train-mlogloss:0.02258	eval-mlogloss:0.01773
[102]	train-mlogloss:0.02239	eval-mlogloss:0.01746
[103]	train-mlogloss:0.02227	eval-mlogloss:0.01715
[104]	train-mlogloss:0.02213	eval-mlogloss:0.01677
[105]	train-mlogloss:0.02207	eval-mlogloss:0.01742
[106]	train-mlogloss:0.02209	eval-mlogloss:0.01737
[107]	train-mlogloss:0.02208	eval-mlogloss:0.01619
[108]	train-mlogloss:0.02205	eval-mlogloss:0.01641
[109]	train-mlogloss:0.02196	eval-mlogloss:0.01666
[110]	train-mlogloss:0.02191	eval-mlogloss:0.01646
[111]	train-mlogloss:0.02194	eval-mlogloss:0.01633
[112]	train-mlogloss:0.02179	eval-mlogloss:0.01688
[113]	train-mlogloss:0.02181	eval-mlogloss:0.01595
[114]	train-mlogloss:0.02170	eval-mlogloss:0.01635
[115]	train-mlogloss:0.02169	eval-mlogloss:0.01676
[116]	train-mlogloss:0.02175	eval-mlogloss:0.01700
[117]	train-mlogloss:0.02163	eval-mlogloss:0.01640
[118]	train-mlogloss:0.02162	eval-mlogloss:0.01671
[119]	train-mlogloss:0.02157	eval-mlogloss:0.01731
[120]	train-mlogloss:0.02158	eval-mlogloss:0.01688
[121]	train-mlogloss:0.02161	eval-mlogloss:0.01712
[122]	train-mlogloss:0.02157	eval-mlogloss:0.01702
[123]	train-mlogloss:0.02150	eval-mlogloss:0.01726
[124]	train-mlogloss:0.02146	eval-mlogloss:0.01717
[125]	train-mlogloss:0.02139	eval-mlogloss:0.01654
[126]	train-mlogloss:0.02118	eval-mlogloss:0.01635
[127]	train-mlogloss:0.02115	eval-mlogloss:0.01573
[128]	train-mlogloss:0.02117	eval-mlogloss:0.01515
[129]	train-mlogloss:0.02102	eval-mlogloss:0.01552
[130]	train-mlogloss:0.02104	eval-mlogloss:0.01516
[131]	train-mlogloss:0.02097	eval-mlogloss:0.01538
[132]	train-mlogloss:0.02091	eval-mlogloss:0.01517
[133]	train-mlogloss:0.02092	eval-mlogloss:0.01542
[134]	train-mlogloss:0.02094	eval-mlogloss:0.01560
[135]	train-mlogloss:0.02095	eval-mlogloss:0.01564
[136]	train-mlogloss:0.02104	eval-mlogloss:0.01563
[137]	train-mlogloss:0.02103	eval-mlogloss:0.01565
[138]	train-mlogloss:0.02102	eval-mlogloss:0.01589
[139]	train-mlogloss:0.02094	eval-mlogloss:0.01624
[140]	train-mlogloss:0.02053	eval-mlogloss:0.01576
[141]	train-mlogloss:0.02056	eval-mlogloss:0.01557
[142]	train-mlogloss:0.02052	eval-mlogloss:0.01527
[143]	train-mlogloss:0.02048	eval-mlogloss:0.01518
[144]	train-mlogloss:0.02050	eval-mlogloss:0.01534
[145]	train-mlogloss:0.02053	eval-mlogloss:0.01483
[146]	train-mlogloss:0.02045	eval-mlogloss:0.01518
[147]	train-mlogloss:0.02041	eval-mlogloss:0.01501
[148]	train-mlogloss:0.02036	eval-mlogloss:0.01555
[149]	train-mlogloss:0.02036	eval-mlogloss:0.01560
[150]	train-mlogloss:0.02033	eval-mlogloss:0.01562
[151]	train-mlogloss:0.02029	eval-mlogloss:0.01606
[152]	train-mlogloss:0.02037	eval-mlogloss:0.01563
[153]	train-mlogloss:0.02035	eval-mlogloss:0.01566
[154]	train-mlogloss:0.02026	eval-mlogloss:0.01612
[155]	train-mlogloss:0.02033	eval-mlogloss:0.01615
[156]	train-mlogloss:0.02036	eval-mlogloss:0.01608
[157]	train-mlogloss:0.02027	eval-mlogloss:0.01554
[158]	train-mlogloss:0.02026	eval-mlogloss:0.01590
[159]	train-mlogloss:0.02019	eval-mlogloss:0.01581
[160]	train-mlogloss:0.02013	eval-mlogloss:0.01537
[161]	train-mlogloss:0.02012	eval-mlogloss:0.01505
[162]	train-mlogloss:0.02009	eval-mlogloss:0.01549
[163]	train-mlogloss:0.02007	eval-mlogloss:0.01560
[164]	train-mlogloss:0.02003	eval-mlogloss:0.01558
[165]	train-mlogloss:0.02006	eval-mlogloss:0.01583
[166]	train-mlogloss:0.02003	eval-mlogloss:0.01579
[167]	train-mlogloss:0.02003	eval-mlogloss:0.01561
[168]	train-mlogloss:0.02010	eval-mlogloss:0.01665
[169]	train-mlogloss:0.02006	eval-mlogloss:0.01618
[170]	train-mlogloss:0.02002	eval-mlogloss:0.01595
[171]	train-mlogloss:0.01995	eval-mlogloss:0.01564
[172]	train-mlogloss:0.01995	eval-mlogloss:0.01553
[173]	train-mlogloss:0.01992	eval-mlogloss:0.01561
[174]	train-mlogloss:0.01986	eval-mlogloss:0.01542
[175]	train-mlogloss:0.01986	eval-mlogloss:0.01502

[I 2026-02-27 06:06:47,324] Trial 1 finished with value: 1.0 and parameters: {'lambda': 0.005314957923391696, 'alpha': 0.005846818075732081, 'eta': 0.25181031321972147, 'gamma': 4.498859234670278e-06, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.7669667652124709, 'colsample_bytree': 0.7236724104495766}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.97393	eval-mlogloss:0.96632
[1]	train-mlogloss:0.87005	eval-mlogloss:0.85655
[2]	train-mlogloss:0.78035	eval-mlogloss:0.76289
[3]	train-mlogloss:0.70257	eval-mlogloss:0.68098
[4]	train-mlogloss:0.63716	eval-mlogloss:0.61261
[5]	train-mlogloss:0.57845	eval-mlogloss:0.54843
[6]	train-mlogloss:0.52822	eval-mlogloss:0.49664
[7]	train-mlogloss:0.48384	eval-mlogloss:0.45091
[8]	train-mlogloss:0.44651	eval-mlogloss:0.40989
[9]	train-mlogloss:0.41802	eval-mlogloss:0.37993
[10]	train-mlogloss:0.38925	eval-mlogloss:0.34696
[11]	train-mlogloss:0.36522	eval-mlogloss:0.31998
[12]	train-mlogloss:0.34638	eval-mlogloss:0.29767
[13]	train-mlogloss:0.32963	eval-mlogloss:0.27733
[14]	train-mlogloss:0.31298	eval-mlogloss:0.26000
[15]	train-mlogloss:0.29870	eval-mlogloss:0.24453
[16]	train-mlogloss:0.28500	eval-mlogloss:0.22901
[17]	train-mlogloss:0.27444	eval-mlogloss:0.21741
[18]	train-mlogloss:0.26932	eval-mlogloss:0.21134
[19]	train-mlogloss:0.26477	eval-mlogloss:0.20564
[20]	train-mlogloss:0.26434	eval-mlogloss:0.20448
[21]	train-mlogloss:0.26369	eval-mlogloss:0.20286
[22]	train-mlogloss:0.25983	eval-mlogloss:0.19679
[23]	train-mlogloss:0.24952	eval-mlogloss:0.18583
[24]	train-mlogloss:0.24927	eval-mlogloss:0.18574
[25]	train-mlogloss:0.24525	eval-mlogloss:0.18049
[26]	train-mlogloss:0.24524	eval-mlogloss:0.18056
[27]	train-mlogloss:0.24506	eval-mlogloss:0.18040
[28]	train-mlogloss:0.24474	eval-mlogloss:0.18013
[29]	train-mlogloss:0.24446	eval-mlogloss:0.17925
[30]	train-mlogloss:0.24421	eval-mlogloss:0.17922
[31]	train-mlogloss:0.24388	eval-mlogloss:0.17821
[32]	train-mlogloss:0.24373	eval-mlogloss:0.17821
[33]	train-mlogloss:0.24338	eval-mlogloss:0.17670
[34]	train-mlogloss:0.24317	eval-mlogloss:0.17596
[35]	train-mlogloss:0.24301	eval-mlogloss:0.17595
[36]	train-mlogloss:0.24155	eval-mlogloss:0.17395
[37]	train-mlogloss:0.23836	eval-mlogloss:0.16892
[38]	train-mlogloss:0.23822	eval-mlogloss:0.16863
[39]	train-mlogloss:0.23790	eval-mlogloss:0.16847
[40]	train-mlogloss:0.23771	eval-mlogloss:0.16841
[41]	train-mlogloss:0.23747	eval-mlogloss:0.16845
[42]	train-mlogloss:0.23721	eval-mlogloss:0.16744
[43]	train-mlogloss:0.23465	eval-mlogloss:0.16437
[44]	train-mlogloss:0.23455	eval-mlogloss:0.16439
[45]	train-mlogloss:0.23434	eval-mlogloss:0.16437
[46]	train-mlogloss:0.23420	eval-mlogloss:0.16401
[47]	train-mlogloss:0.23409	eval-mlogloss:0.16393
[48]	train-mlogloss:0.23410	eval-mlogloss:0.16394
[49]	train-mlogloss:0.23397	eval-mlogloss:0.16330
[50]	train-mlogloss:0.23399	eval-mlogloss:0.16328
[51]	train-mlogloss:0.23385	eval-mlogloss:0.16347
[52]	train-mlogloss:0.23366	eval-mlogloss:0.16346
[53]	train-mlogloss:0.23356	eval-mlogloss:0.16364
[54]	train-mlogloss:0.23346	eval-mlogloss:0.16335
[55]	train-mlogloss:0.23320	eval-mlogloss:0.16328
[56]	train-mlogloss:0.23311	eval-mlogloss:0.16316
[57]	train-mlogloss:0.23313	eval-mlogloss:0.16310
[58]	train-mlogloss:0.23314	eval-mlogloss:0.16309
[59]	train-mlogloss:0.23290	eval-mlogloss:0.16302
[60]	train-mlogloss:0.23287	eval-mlogloss:0.16306
[61]	train-mlogloss:0.23262	eval-mlogloss:0.16304
[62]	train-mlogloss:0.23249	eval-mlogloss:0.16302
[63]	train-mlogloss:0.23250	eval-mlogloss:0.16297
[64]	train-mlogloss:0.23237	eval-mlogloss:0.16222
[65]	train-mlogloss:0.23236	eval-mlogloss:0.16228
[66]	train-mlogloss:0.23225	eval-mlogloss:0.16240
[67]	train-mlogloss:0.23224	eval-mlogloss:0.16239
[68]	train-mlogloss:0.23198	eval-mlogloss:0.16236
[69]	train-mlogloss:0.23181	eval-mlogloss:0.16228
[70]	train-mlogloss:0.23173	eval-mlogloss:0.16228
[71]	train-mlogloss:0.23158	eval-mlogloss:0.16148
[72]	train-mlogloss:0.23148	eval-mlogloss:0.16147
[73]	train-mlogloss:0.23142	eval-mlogloss:0.16134
[74]	train-mlogloss:0.23129	eval-mlogloss:0.16143
[75]	train-mlogloss:0.23117	eval-mlogloss:0.16148
[76]	train-mlogloss:0.23112	eval-mlogloss:0.16169
[77]	train-mlogloss:0.23103	eval-mlogloss:0.16168
[78]	train-mlogloss:0.23107	eval-mlogloss:0.16182
[79]	train-mlogloss:0.23106	eval-mlogloss:0.16186
[80]	train-mlogloss:0.23092	eval-mlogloss:0.16183
[81]	train-mlogloss:0.23092	eval-mlogloss:0.16192
[82]	train-mlogloss:0.23091	eval-mlogloss:0.16186
[83]	train-mlogloss:0.23075	eval-mlogloss:0.16168
[84]	train-mlogloss:0.23061	eval-mlogloss:0.16159
[85]	train-mlogloss:0.23049	eval-mlogloss:0.16149
[86]	train-mlogloss:0.23040	eval-mlogloss:0.16086
[87]	train-mlogloss:0.23028	eval-mlogloss:0.16086
[88]	train-mlogloss:0.23019	eval-mlogloss:0.16081
[89]	train-mlogloss:0.22992	eval-mlogloss:0.16058
[90]	train-mlogloss:0.22993	eval-mlogloss:0.16064
[91]	train-mlogloss:0.22993	eval-mlogloss:0.16058
[92]	train-mlogloss:0.22962	eval-mlogloss:0.16030
[93]	train-mlogloss:0.22959	eval-mlogloss:0.16016
[94]	train-mlogloss:0.22951	eval-mlogloss:0.16016
[95]	train-mlogloss:0.22941	eval-mlogloss:0.16017
[96]	train-mlogloss:0.22929	eval-mlogloss:0.16020
[97]	train-mlogloss:0.22916	eval-mlogloss:0.16017
[98]	train-mlogloss:0.22917	eval-mlogloss:0.16020
[99]	train-mlogloss:0.22906	eval-mlogloss:0.16022
[100]	train-mlogloss:0.22904	eval-mlogloss:0.16030
[101]	train-mlogloss:0.22891	eval-mlogloss:0.16027
[102]	train-mlogloss:0.22887	eval-mlogloss:0.16031
[103]	train-mlogloss:0.22880	eval-mlogloss:0.16012
[104]	train-mlogloss:0.22879	eval-mlogloss:0.16015
[105]	train-mlogloss:0.22869	eval-mlogloss:0.16006
[106]	train-mlogloss:0.22860	eval-mlogloss:0.15997
[107]	train-mlogloss:0.22845	eval-mlogloss:0.16004
[108]	train-mlogloss:0.22840	eval-mlogloss:0.16008
[109]	train-mlogloss:0.22832	eval-mlogloss:0.15997
[110]	train-mlogloss:0.22830	eval-mlogloss:0.15993
[111]	train-mlogloss:0.22824	eval-mlogloss:0.15989
[112]	train-mlogloss:0.22821	eval-mlogloss:0.15979
[113]	train-mlogloss:0.22821	eval-mlogloss:0.15981
[114]	train-mlogloss:0.22813	eval-mlogloss:0.15987
[115]	train-mlogloss:0.22815	eval-mlogloss:0.15994
[116]	train-mlogloss:0.22804	eval-mlogloss:0.15989
[117]	train-mlogloss:0.22794	eval-mlogloss:0.15986
[118]	train-mlogloss:0.22794	eval-mlogloss:0.15989
[119]	train-mlogloss:0.22786	eval-mlogloss:0.15981
[120]	train-mlogloss:0.22782	eval-mlogloss:0.15990
[121]	train-mlogloss:0.22777	eval-mlogloss:0.15998
[122]	train-mlogloss:0.22769	eval-mlogloss:0.15998
[123]	train-mlogloss:0.22767	eval-mlogloss:0.16001
[124]	train-mlogloss:0.22757	eval-mlogloss:0.15942
[125]	train-mlogloss:0.22756	eval-mlogloss:0.15938
[126]	train-mlogloss:0.22749	eval-mlogloss:0.15945
[127]	train-mlogloss:0.22734	eval-mlogloss:0.15927
[128]	train-mlogloss:0.22733	eval-mlogloss:0.15931
[129]	train-mlogloss:0.22719	eval-mlogloss:0.15920
[130]	train-mlogloss:0.22713	eval-mlogloss:0.15919
[131]	train-mlogloss:0.22714	eval-mlogloss:0.15926
[132]	train-mlogloss:0.22712	eval-mlogloss:0.15908
[133]	train-mlogloss:0.22712	eval-mlogloss:0.15910
[134]	train-mlogloss:0.22713	eval-mlogloss:0.15917
[135]	train-mlogloss:0.22702	eval-mlogloss:0.15921
[136]	train-mlogloss:0.22702	eval-mlogloss:0.15919
[137]	train-mlogloss:0.22683	eval-mlogloss:0.15898
[138]	train-mlogloss:0.22679	eval-mlogloss:0.15884
[139]	train-mlogloss:0.22671	eval-mlogloss:0.15881
[140]	train-mlogloss:0.22668	eval-mlogloss:0.15878
[141]	train-mlogloss:0.22669	eval-mlogloss:0.15887
[142]	train-mlogloss:0.22671	eval-mlogloss:0.15899
[143]	train-mlogloss:0.22672	eval-mlogloss:0.15902
[144]	train-mlogloss:0.22674	eval-mlogloss:0.15909
[145]	train-mlogloss:0.22670	eval-mlogloss:0.15917
[146]	train-mlogloss:0.22653	eval-mlogloss:0.15891
[147]	train-mlogloss:0.22639	eval-mlogloss:0.15836
[148]	train-mlogloss:0.22639	eval-mlogloss:0.15836
[149]	train-mlogloss:0.22642	eval-mlogloss:0.15849
[150]	train-mlogloss:0.22633	eval-mlogloss:0.15841
[151]	train-mlogloss:0.22632	eval-mlogloss:0.15827
[152]	train-mlogloss:0.22621	eval-mlogloss:0.15838
[153]	train-mlogloss:0.22618	eval-mlogloss:0.15843
[154]	train-mlogloss:0.22616	eval-mlogloss:0.15825
[155]	train-mlogloss:0.22608	eval-mlogloss:0.15828
[156]	train-mlogloss:0.22609	eval-mlogloss:0.15820
[157]	train-mlogloss:0.22609	eval-mlogloss:0.15817
[158]	train-mlogloss:0.22607	eval-mlogloss:0.15824
[159]	train-mlogloss:0.22595	eval-mlogloss:0.15820
[160]	train-mlogloss:0.22583	eval-mlogloss:0.15810
[161]	train-mlogloss:0.22579	eval-mlogloss:0.15820
[162]	train-mlogloss:0.22575	eval-mlogloss:0.15823
[163]	train-mlogloss:0.22575	eval-mlogloss:0.15827
[164]	train-mlogloss:0.22575	eval-mlogloss:0.15816
[165]	train-mlogloss:0.22569	eval-mlogloss:0.15804
[166]	train-mlogloss:0.22560	eval-mlogloss:0.15797
[167]	train-mlogloss:0.22558	eval-mlogloss:0.15791
[168]	train-mlogloss:0.22557	eval-mlogloss:0.15785
[169]	train-mlogloss:0.22552	eval-mlogloss:0.15782
[170]	train-mlogloss:0.22551	eval-mlogloss:0.15778
[171]	train-mlogloss:0.22548	eval-mlogloss:0.15777
[172]	train-mlogloss:0.22548	eval-mlogloss:0.15775
[173]	train-mlogloss:0.22548	eval-mlogloss:0.15774
[174]	train-mlogloss:0.22544	eval-mlogloss:0.15786
[175]	train-mlogloss:0.22543	eval-mlogloss:0.15777
[176]	train-mlogloss:0.22533	eval-mlogloss:0.15777
[177]	train-mlogloss:0.22528	eval-mlogloss:0.15757
[178]	train-mlogloss:0.22527	eval-mlogloss:0.15754
[179]	train-mlogloss:0.22528	eval-mlogloss:0.15755
[180]	train-mlogloss:0.22529	eval-mlogloss:0.15767
[181]	train-mlogloss:0.22527	eval-mlogloss:0.15767
[182]	train-mlogloss:0.22517	eval-mlogloss:0.15754
[183]	train-mlogloss:0.22516	eval-mlogloss:0.15751
[184]	train-mlogloss:0.22511	eval-mlogloss:0.15750
[185]	train-mlogloss:0.22508	eval-mlogloss:0.15754
[186]	train-mlogloss:0.22502	eval-mlogloss:0.15746
[187]	train-mlogloss:0.22503	eval-mlogloss:0.15744
[188]	train-mlogloss:0.22502	eval-mlogloss:0.15745
[189]	train-mlogloss:0.22502	eval-mlogloss:0.15743
[190]	train-mlogloss:0.22504	eval-mlogloss:0.15749
[191]	train-mlogloss:0.22504	eval-mlogloss:0.15752
[192]	train-mlogloss:0.22504	eval-mlogloss:0.15745
[193]	train-mlogloss:0.22505	eval-mlogloss:0.15742
[194]	train-mlogloss:0.22500	eval-mlogloss:0.15747
[195]	train-mlogloss:0.22499	eval-mlogloss:0.15752
[196]	train-mlogloss:0.22493	eval-mlogloss:0.15761
[197]	train-mlogloss:0.22493	eval-mlogloss:0.15761
[198]	train-mlogloss:0.22493	eval-mlogloss:0.15756
[199]	train-mlogloss:0.22491	eval-mlogloss:0.15759
[200]	train-mlogloss:0.22490	eval-mlogloss:0.15750
[201]	train-mlogloss:0.22492	eval-mlogloss:0.15733
[202]	train-mlogloss:0.22492	eval-mlogloss:0.15731
[203]	train-mlogloss:0.22490	eval-mlogloss:0.15745
[204]	train-mlogloss:0.22487	eval-mlogloss:0.15745
[205]	train-mlogloss:0.22474	eval-mlogloss:0.15734
[206]	train-mlogloss:0.22476	eval-mlogloss:0.15742
[207]	train-mlogloss:0.22470	eval-mlogloss:0.15739
[208]	train-mlogloss:0.22471	eval-mlogloss:0.15743
[209]	train-mlogloss:0.22467	eval-mlogloss:0.15742
[210]	train-mlogloss:0.22458	eval-mlogloss:0.15661
[211]	train-mlogloss:0.22457	eval-mlogloss:0.15652
[212]	train-mlogloss:0.22451	eval-mlogloss:0.15656
[213]	train-mlogloss:0.22451	eval-mlogloss:0.15655
[214]	train-mlogloss:0.22451	eval-mlogloss:0.15656
[215]	train-mlogloss:0.22450	eval-mlogloss:0.15659
[216]	train-mlogloss:0.22450	eval-mlogloss:0.15664
[217]	train-mlogloss:0.22449	eval-mlogloss:0.15657
[218]	train-mlogloss:0.22449	eval-mlogloss:0.15656
[219]	train-mlogloss:0.22450	eval-mlogloss:0.15653
[220]	train-mlogloss:0.22448	eval-mlogloss:0.15644
[221]	train-mlogloss:0.22447	eval-mlogloss:0.15650
[222]	train-mlogloss:0.22443	eval-mlogloss:0.15660
[223]	train-mlogloss:0.22434	eval-mlogloss:0.15648
[224]	train-mlogloss:0.22428	eval-mlogloss:0.15602
[225]	train-mlogloss:0.22429	eval-mlogloss:0.15604
[226]	train-mlogloss:0.22429	eval-mlogloss:0.15597
[227]	train-mlogloss:0.22429	eval-mlogloss:0.15597
[228]	train-mlogloss:0.22427	eval-mlogloss:0.15603
[229]	train-mlogloss:0.22425	eval-mlogloss:0.15613
[230]	train-mlogloss:0.22421	eval-mlogloss:0.15615
[231]	train-mlogloss:0.22418	eval-mlogloss:0.15627
[232]	train-mlogloss:0.22418	eval-mlogloss:0.15625
[233]	train-mlogloss:0.22418	eval-mlogloss:0.15619
[234]	train-mlogloss:0.22415	eval-mlogloss:0.15629
[235]	train-mlogloss:0.22415	eval-mlogloss:0.15624
[236]	train-mlogloss:0.22407	eval-mlogloss:0.15620
[237]	train-mlogloss:0.22406	eval-mlogloss:0.15614
[238]	train-mlogloss:0.22403	eval-mlogloss:0.15610
[239]	train-mlogloss:0.22401	eval-mlogloss:0.15612
[240]	train-mlogloss:0.22401	eval-mlogloss:0.15621
[241]	train-mlogloss:0.22399	eval-mlogloss:0.15623
[242]	train-mlogloss:0.22399	eval-mlogloss:0.15626
[243]	train-mlogloss:0.22399	eval-mlogloss:0.15624
[244]	train-mlogloss:0.22399	eval-mlogloss:0.15628
[245]	train-mlogloss:0.22398	eval-mlogloss:0.15619
[246]	train-mlogloss:0.22399	eval-mlogloss:0.15602
[247]	train-mlogloss:0.22400	eval-mlogloss:0.15595
[248]	train-mlogloss:0.22400	eval-mlogloss:0.15596
[249]	train-mlogloss:0.22400	eval-mlogloss:0.15594
[250]	train-mlogloss:0.22399	eval-mlogloss:0.15596
[251]	train-mlogloss:0.22398	eval-mlogloss:0.15603
[252]	train-mlogloss:0.22398	eval-mlogloss:0.15595
[253]	train-mlogloss:0.22398	eval-mlogloss:0.15594
[254]	train-mlogloss:0.22391	eval-mlogloss:0.15593
[255]	train-mlogloss:0.22389	eval-mlogloss:0.15585
[256]	train-mlogloss:0.22389	eval-mlogloss:0.15591
[257]	train-mlogloss:0.22390	eval-mlogloss:0.15582
[258]	train-mlogloss:0.22390	eval-mlogloss:0.15579
[259]	train-mlogloss:0.22390	eval-mlogloss:0.15578
[260]	train-mlogloss:0.22389	eval-mlogloss:0.15587
[261]	train-mlogloss:0.22388	eval-mlogloss:0.15598
[262]	train-mlogloss:0.22389	eval-mlogloss:0.15604
[263]	train-mlogloss:0.22392	eval-mlogloss:0.15591
[264]	train-mlogloss:0.22381	eval-mlogloss:0.15576
[265]	train-mlogloss:0.22384	eval-mlogloss:0.15571
[266]	train-mlogloss:0.22383	eval-mlogloss:0.15583
[267]	train-mlogloss:0.22374	eval-mlogloss:0.15574
[268]	train-mlogloss:0.22374	eval-mlogloss:0.15574
[269]	train-mlogloss:0.22359	eval-mlogloss:0.15569
[270]	train-mlogloss:0.22357	eval-mlogloss:0.15562
[271]	train-mlogloss:0.22357	eval-mlogloss:0.15560
[272]	train-mlogloss:0.22357	eval-mlogloss:0.15568
[273]	train-mlogloss:0.22356	eval-mlogloss:0.15556
[274]	train-mlogloss:0.22357	eval-mlogloss:0.15556
[275]	train-mlogloss:0.22352	eval-mlogloss:0.15561
[276]	train-mlogloss:0.22348	eval-mlogloss:0.15564
[277]	train-mlogloss:0.22346	eval-mlogloss:0.15553
[278]	train-mlogloss:0.22345	eval-mlogloss:0.15545
[279]	train-mlogloss:0.22343	eval-mlogloss:0.15551
[280]	train-mlogloss:0.22341	eval-mlogloss:0.15539
[281]	train-mlogloss:0.22342	eval-mlogloss:0.15546
[282]	train-mlogloss:0.22341	eval-mlogloss:0.15543
[283]	train-mlogloss:0.22338	eval-mlogloss:0.15530
[284]	train-mlogloss:0.22338	eval-mlogloss:0.15537
[285]	train-mlogloss:0.22338	eval-mlogloss:0.15528
[286]	train-mlogloss:0.22338	eval-mlogloss:0.15542
[287]	train-mlogloss:0.22338	eval-mlogloss:0.15535
[288]	train-mlogloss:0.22338	eval-mlogloss:0.15544
[289]	train-mlogloss:0.22337	eval-mlogloss:0.15540
[290]	train-mlogloss:0.22337	eval-mlogloss:0.15530
[291]	train-mlogloss:0.22337	eval-mlogloss:0.15546
[292]	train-mlogloss:0.22331	eval-mlogloss:0.15492
[293]	train-mlogloss:0.22331	eval-mlogloss:0.15501
[294]	train-mlogloss:0.22329	eval-mlogloss:0.15496
[295]	train-mlogloss:0.22327	eval-mlogloss:0.15489
[296]	train-mlogloss:0.22328	eval-mlogloss:0.15497
[297]	train-mlogloss:0.22332	eval-mlogloss:0.15521
[298]	train-mlogloss:0.22330	eval-mlogloss:0.15499
[299]	train-mlogloss:0.22327	eval-mlogloss:0.15484

[I 2026-02-27 06:06:48,196] Trial 2 finished with value: 1.0 and parameters: {'lambda': 3.237174291742934e-05, 'alpha': 0.000557771279230361, 'eta': 0.0991788040872926, 'gamma': 2.628745984492002e-06, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.8125783512587283, 'colsample_bytree': 0.9215964057782662}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.95916	eval-mlogloss:0.96701
[1]	train-mlogloss:0.69037	eval-mlogloss:0.67995

[I 2026-02-27 06:06:48,208] Trial 3 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.95447	eval-mlogloss:0.94982
[1]	train-mlogloss:0.80986	eval-mlogloss:0.79816

[I 2026-02-27 06:06:48,221] Trial 4 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91955	eval-mlogloss:0.91240
[1]	train-mlogloss:0.70970	eval-mlogloss:0.69341

[I 2026-02-27 06:06:48,232] Trial 5 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.05343	eval-mlogloss:1.05294
[1]	train-mlogloss:1.00221	eval-mlogloss:0.99551
[2]	train-mlogloss:0.94187	eval-mlogloss:0.93224
[3]	train-mlogloss:0.88580	eval-mlogloss:0.87324
[4]	train-mlogloss:0.83709	eval-mlogloss:0.82328
[5]	train-mlogloss:0.78738	eval-mlogloss:0.77110
[6]	train-mlogloss:0.74431	eval-mlogloss:0.72596
[7]	train-mlogloss:0.70955	eval-mlogloss:0.69371
[8]	train-mlogloss:0.67478	eval-mlogloss:0.65541
[9]	train-mlogloss:0.63950	eval-mlogloss:0.61854
[10]	train-mlogloss:0.60749	eval-mlogloss:0.58519
[11]	train-mlogloss:0.57713	eval-mlogloss:0.55210
[12]	train-mlogloss:0.56013	eval-mlogloss:0.53520
[13]	train-mlogloss:0.53479	eval-mlogloss:0.50647
[14]	train-mlogloss:0.51936	eval-mlogloss:0.49072
[15]	train-mlogloss:0.49692	eval-mlogloss:0.46704
[16]	train-mlogloss:0.47895	eval-mlogloss:0.44831
[17]	train-mlogloss:0.46306	eval-mlogloss:0.43144
[18]	train-mlogloss:0.44506	eval-mlogloss:0.41239
[19]	train-mlogloss:0.42971	eval-mlogloss:0.39551
[20]	train-mlogloss:0.41652	eval-mlogloss:0.38039
[21]	train-mlogloss:0.40486	eval-mlogloss:0.36758
[22]	train-mlogloss:0.39314	eval-mlogloss:0.35512
[23]	train-mlogloss:0.38079	eval-mlogloss:0.34196
[24]	train-mlogloss:0.36619	eval-mlogloss:0.32490
[25]	train-mlogloss:0.35501	eval-mlogloss:0.31169
[26]	train-mlogloss:0.34561	eval-mlogloss:0.30136
[27]	train-mlogloss:0.33822	eval-mlogloss:0.29397
[28]	train-mlogloss:0.33165	eval-mlogloss:0.28734
[29]	train-mlogloss:0.32218	eval-mlogloss:0.27672
[30]	train-mlogloss:0.31499	eval-mlogloss:0.26966
[31]	train-mlogloss:0.30651	eval-mlogloss:0.26044
[32]	train-mlogloss:0.30168	eval-mlogloss:0.25491
[33]	train-mlogloss:0.29664	eval-mlogloss:0.24836
[34]	train-mlogloss:0.29091	eval-mlogloss:0.24166
[35]	train-mlogloss:0.28650	eval-mlogloss:0.23610
[36]	train-mlogloss:0.27949	eval-mlogloss:0.22862
[37]	train-mlogloss:0.27589	eval-mlogloss:0.22408
[38]	train-mlogloss:0.27129	eval-mlogloss:0.21891
[39]	train-mlogloss:0.26766	eval-mlogloss:0.21450
[40]	train-mlogloss:0.26309	eval-mlogloss:0.20934
[41]	train-mlogloss:0.26045	eval-mlogloss:0.20622
[42]	train-mlogloss:0.25738	eval-mlogloss:0.20163
[43]	train-mlogloss:0.25389	eval-mlogloss:0.19799
[44]	train-mlogloss:0.24850	eval-mlogloss:0.19172
[45]	train-mlogloss:0.24825	eval-mlogloss:0.19148
[46]	train-mlogloss:0.24493	eval-mlogloss:0.18808
[47]	train-mlogloss:0.24486	eval-mlogloss:0.18797
[48]	train-mlogloss:0.24318	eval-mlogloss:0.18509
[49]	train-mlogloss:0.24084	eval-mlogloss:0.18181
[50]	train-mlogloss:0.23777	eval-mlogloss:0.17803
[51]	train-mlogloss:0.23621	eval-mlogloss:0.17589
[52]	train-mlogloss:0.23595	eval-mlogloss:0.17583
[53]	train-mlogloss:0.23590	eval-mlogloss:0.17588
[54]	train-mlogloss:0.23572	eval-mlogloss:0.17542
[55]	train-mlogloss:0.23292	eval-mlogloss:0.17154
[56]	train-mlogloss:0.23282	eval-mlogloss:0.17144
[57]	train-mlogloss:0.23264	eval-mlogloss:0.17109
[58]	train-mlogloss:0.23264	eval-mlogloss:0.17106
[59]	train-mlogloss:0.23232	eval-mlogloss:0.17093
[60]	train-mlogloss:0.23223	eval-mlogloss:0.17085
[61]	train-mlogloss:0.23188	eval-mlogloss:0.17072
[62]	train-mlogloss:0.23144	eval-mlogloss:0.17057
[63]	train-mlogloss:0.23129	eval-mlogloss:0.16979
[64]	train-mlogloss:0.23103	eval-mlogloss:0.16954
[65]	train-mlogloss:0.23094	eval-mlogloss:0.16946
[66]	train-mlogloss:0.23062	eval-mlogloss:0.16919
[67]	train-mlogloss:0.23024	eval-mlogloss:0.16872
[68]	train-mlogloss:0.23012	eval-mlogloss:0.16863
[69]	train-mlogloss:0.22926	eval-mlogloss:0.16752
[70]	train-mlogloss:0.22920	eval-mlogloss:0.16733
[71]	train-mlogloss:0.22890	eval-mlogloss:0.16724
[72]	train-mlogloss:0.22879	eval-mlogloss:0.16696
[73]	train-mlogloss:0.22851	eval-mlogloss:0.16654
[74]	train-mlogloss:0.22837	eval-mlogloss:0.16618
[75]	train-mlogloss:0.22842	eval-mlogloss:0.16627
[76]	train-mlogloss:0.22817	eval-mlogloss:0.16584
[77]	train-mlogloss:0.22782	eval-mlogloss:0.16530
[78]	train-mlogloss:0.22703	eval-mlogloss:0.16552
[79]	train-mlogloss:0.22530	eval-mlogloss:0.16339
[80]	train-mlogloss:0.22494	eval-mlogloss:0.16323
[81]	train-mlogloss:0.22496	eval-mlogloss:0.16319
[82]	train-mlogloss:0.22491	eval-mlogloss:0.16322
[83]	train-mlogloss:0.22496	eval-mlogloss:0.16328
[84]	train-mlogloss:0.22328	eval-mlogloss:0.16124
[85]	train-mlogloss:0.22296	eval-mlogloss:0.16090
[86]	train-mlogloss:0.22297	eval-mlogloss:0.16104
[87]	train-mlogloss:0.22269	eval-mlogloss:0.16093
[88]	train-mlogloss:0.22230	eval-mlogloss:0.16035
[89]	train-mlogloss:0.22171	eval-mlogloss:0.15955
[90]	train-mlogloss:0.22159	eval-mlogloss:0.15946
[91]	train-mlogloss:0.22145	eval-mlogloss:0.15867
[92]	train-mlogloss:0.22117	eval-mlogloss:0.15831
[93]	train-mlogloss:0.22094	eval-mlogloss:0.15727
[94]	train-mlogloss:0.22083	eval-mlogloss:0.15679
[95]	train-mlogloss:0.22061	eval-mlogloss:0.15676
[96]	train-mlogloss:0.22061	eval-mlogloss:0.15683
[97]	train-mlogloss:0.21984	eval-mlogloss:0.15613
[98]	train-mlogloss:0.21971	eval-mlogloss:0.15600
[99]	train-mlogloss:0.21835	eval-mlogloss:0.15402
[100]	train-mlogloss:0.21774	eval-mlogloss:0.15315
[101]	train-mlogloss:0.21752	eval-mlogloss:0.15307
[102]	train-mlogloss:0.21741	eval-mlogloss:0.15306
[103]	train-mlogloss:0.21741	eval-mlogloss:0.15307
[104]	train-mlogloss:0.21740	eval-mlogloss:0.15308
[105]	train-mlogloss:0.21730	eval-mlogloss:0.15287
[106]	train-mlogloss:0.21715	eval-mlogloss:0.15291
[107]	train-mlogloss:0.21732	eval-mlogloss:0.15336
[108]	train-mlogloss:0.21704	eval-mlogloss:0.15321
[109]	train-mlogloss:0.21687	eval-mlogloss:0.15295
[110]	train-mlogloss:0.21686	eval-mlogloss:0.15303
[111]	train-mlogloss:0.21679	eval-mlogloss:0.15279
[112]	train-mlogloss:0.21526	eval-mlogloss:0.15090
[113]	train-mlogloss:0.21525	eval-mlogloss:0.15088
[114]	train-mlogloss:0.21515	eval-mlogloss:0.15028
[115]	train-mlogloss:0.21530	eval-mlogloss:0.15104
[116]	train-mlogloss:0.21531	eval-mlogloss:0.15109
[117]	train-mlogloss:0.21510	eval-mlogloss:0.15058
[118]	train-mlogloss:0.21505	eval-mlogloss:0.15046
[119]	train-mlogloss:0.21496	eval-mlogloss:0.15020
[120]	train-mlogloss:0.21461	eval-mlogloss:0.14991
[121]	train-mlogloss:0.21454	eval-mlogloss:0.14988
[122]	train-mlogloss:0.21429	eval-mlogloss:0.14989
[123]	train-mlogloss:0.21432	eval-mlogloss:0.14989
[124]	train-mlogloss:0.21307	eval-mlogloss:0.14782
[125]	train-mlogloss:0.21283	eval-mlogloss:0.14758
[126]	train-mlogloss:0.21276	eval-mlogloss:0.14746
[127]	train-mlogloss:0.21266	eval-mlogloss:0.14730

[I 2026-02-27 06:06:48,646] Trial 6 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:1.06900	eval-mlogloss:1.07028
[1]	train-mlogloss:1.03964	eval-mlogloss:1.03986
[2]	train-mlogloss:1.01074	eval-mlogloss:1.01091
[3]	train-mlogloss:0.98313	eval-mlogloss:0.98174
[4]	train-mlogloss:0.95691	eval-mlogloss:0.95521
[5]	train-mlogloss:0.93091	eval-mlogloss:0.92781
[6]	train-mlogloss:0.90667	eval-mlogloss:0.90214
[7]	train-mlogloss:0.88435	eval-mlogloss:0.87930
[8]	train-mlogloss:0.86261	eval-mlogloss:0.85718
[9]	train-mlogloss:0.84115	eval-mlogloss:0.83485
[10]	train-mlogloss:0.82061	eval-mlogloss:0.81453
[11]	train-mlogloss:0.80073	eval-mlogloss:0.79294
[12]	train-mlogloss:0.78214	eval-mlogloss:0.77439
[13]	train-mlogloss:0.76335	eval-mlogloss:0.75481
[14]	train-mlogloss:0.74544	eval-mlogloss:0.73603
[15]	train-mlogloss:0.72766	eval-mlogloss:0.71667
[16]	train-mlogloss:0.71091	eval-mlogloss:0.69866
[17]	train-mlogloss:0.69476	eval-mlogloss:0.68131
[18]	train-mlogloss:0.67908	eval-mlogloss:0.66621
[19]	train-mlogloss:0.66323	eval-mlogloss:0.65020
[20]	train-mlogloss:0.64797	eval-mlogloss:0.63356
[21]	train-mlogloss:0.63309	eval-mlogloss:0.61759
[22]	train-mlogloss:0.61837	eval-mlogloss:0.60221
[23]	train-mlogloss:0.60423	eval-mlogloss:0.58730
[24]	train-mlogloss:0.59125	eval-mlogloss:0.57400
[25]	train-mlogloss:0.57863	eval-mlogloss:0.56017
[26]	train-mlogloss:0.56603	eval-mlogloss:0.54718
[27]	train-mlogloss:0.55402	eval-mlogloss:0.53565
[28]	train-mlogloss:0.54230	eval-mlogloss:0.52289
[29]	train-mlogloss:0.53060	eval-mlogloss:0.51057
[30]	train-mlogloss:0.51917	eval-mlogloss:0.49884
[31]	train-mlogloss:0.50812	eval-mlogloss:0.48722
[32]	train-mlogloss:0.49721	eval-mlogloss:0.47547
[33]	train-mlogloss:0.48707	eval-mlogloss:0.46411
[34]	train-mlogloss:0.47710	eval-mlogloss:0.45406
[35]	train-mlogloss:0.46715	eval-mlogloss:0.44416
[36]	train-mlogloss:0.45745	eval-mlogloss:0.43402
[37]	train-mlogloss:0.44862	eval-mlogloss:0.42478
[38]	train-mlogloss:0.43949	eval-mlogloss:0.41662
[39]	train-mlogloss:0.43054	eval-mlogloss:0.40694
[40]	train-mlogloss:0.42184	eval-mlogloss:0.39793
[41]	train-mlogloss:0.41363	eval-mlogloss:0.38887
[42]	train-mlogloss:0.40568	eval-mlogloss:0.38061
[43]	train-mlogloss:0.39783	eval-mlogloss:0.37187
[44]	train-mlogloss:0.39023	eval-mlogloss:0.36374
[45]	train-mlogloss:0.38249	eval-mlogloss:0.35516
[46]	train-mlogloss:0.37482	eval-mlogloss:0.34692
[47]	train-mlogloss:0.36760	eval-mlogloss:0.33940
[48]	train-mlogloss:0.36045	eval-mlogloss:0.33162
[49]	train-mlogloss:0.35348	eval-mlogloss:0.32438
[50]	train-mlogloss:0.34682	eval-mlogloss:0.31714
[51]	train-mlogloss:0.34035	eval-mlogloss:0.30989
[52]	train-mlogloss:0.33419	eval-mlogloss:0.30410
[53]	train-mlogloss:0.32843	eval-mlogloss:0.29790
[54]	train-mlogloss:0.32244	eval-mlogloss:0.29142
[55]	train-mlogloss:0.31626	eval-mlogloss:0.28457
[56]	train-mlogloss:0.31032	eval-mlogloss:0.27874
[57]	train-mlogloss:0.30471	eval-mlogloss:0.27258
[58]	train-mlogloss:0.29906	eval-mlogloss:0.26632
[59]	train-mlogloss:0.29375	eval-mlogloss:0.26092
[60]	train-mlogloss:0.28847	eval-mlogloss:0.25573
[61]	train-mlogloss:0.28356	eval-mlogloss:0.25055
[62]	train-mlogloss:0.27839	eval-mlogloss:0.24530
[63]	train-mlogloss:0.27351	eval-mlogloss:0.24017
[64]	train-mlogloss:0.26860	eval-mlogloss:0.23528
[65]	train-mlogloss:0.26416	eval-mlogloss:0.23062
[66]	train-mlogloss:0.25957	eval-mlogloss:0.22594
[67]	train-mlogloss:0.25502	eval-mlogloss:0.22119
[68]	train-mlogloss:0.25057	eval-mlogloss:0.21662
[69]	train-mlogloss:0.24657	eval-mlogloss:0.21301
[70]	train-mlogloss:0.24239	eval-mlogloss:0.20879
[71]	train-mlogloss:0.23846	eval-mlogloss:0.20460
[72]	train-mlogloss:0.23472	eval-mlogloss:0.20045
[73]	train-mlogloss:0.23078	eval-mlogloss:0.19611
[74]	train-mlogloss:0.22703	eval-mlogloss:0.19220
[75]	train-mlogloss:0.22335	eval-mlogloss:0.18836
[76]	train-mlogloss:0.21977	eval-mlogloss:0.18453
[77]	train-mlogloss:0.21617	eval-mlogloss:0.18116
[78]	train-mlogloss:0.21261	eval-mlogloss:0.17756
[79]	train-mlogloss:0.20938	eval-mlogloss:0.17401
[80]	train-mlogloss:0.20598	eval-mlogloss:0.17018
[81]	train-mlogloss:0.20265	eval-mlogloss:0.16655
[82]	train-mlogloss:0.19940	eval-mlogloss:0.16311
[83]	train-mlogloss:0.19618	eval-mlogloss:0.15974
[84]	train-mlogloss:0.19306	eval-mlogloss:0.15629
[85]	train-mlogloss:0.18993	eval-mlogloss:0.15312
[86]	train-mlogloss:0.18710	eval-mlogloss:0.15012
[87]	train-mlogloss:0.18417	eval-mlogloss:0.14729
[88]	train-mlogloss:0.18152	eval-mlogloss:0.14441
[89]	train-mlogloss:0.17880	eval-mlogloss:0.14134
[90]	train-mlogloss:0.17620	eval-mlogloss:0.13857
[91]	train-mlogloss:0.17336	eval-mlogloss:0.13613
[92]	train-mlogloss:0.17088	eval-mlogloss:0.13380
[93]	train-mlogloss:0.16835	eval-mlogloss:0.13140
[94]	train-mlogloss:0.16580	eval-mlogloss:0.12897
[95]	train-mlogloss:0.16330	eval-mlogloss:0.12652
[96]	train-mlogloss:0.16067	eval-mlogloss:0.12392
[97]	train-mlogloss:0.15843	eval-mlogloss:0.12184
[98]	train-mlogloss:0.15645	eval-mlogloss:0.11968
[99]	train-mlogloss:0.15408	eval-mlogloss:0.11803
[100]	train-mlogloss:0.15212	eval-mlogloss:0.11602
[101]	train-mlogloss:0.14984	eval-mlogloss:0.11350
[102]	train-mlogloss:0.14781	eval-mlogloss:0.11132
[103]	train-mlogloss:0.14585	eval-mlogloss:0.10932
[104]	train-mlogloss:0.14393	eval-mlogloss:0.10715
[105]	train-mlogloss:0.14218	eval-mlogloss:0.10556
[106]	train-mlogloss:0.14026	eval-mlogloss:0.10378
[107]	train-mlogloss:0.13847	eval-mlogloss:0.10187
[108]	train-mlogloss:0.13679	eval-mlogloss:0.10009
[109]	train-mlogloss:0.13494	eval-mlogloss:0.09840
[110]	train-mlogloss:0.13312	eval-mlogloss:0.09653
[111]	train-mlogloss:0.13159	eval-mlogloss:0.09505
[112]	train-mlogloss:0.12976	eval-mlogloss:0.09344
[113]	train-mlogloss:0.12850	eval-mlogloss:0.09214
[114]	train-mlogloss:0.12701	eval-mlogloss:0.09045
[115]	train-mlogloss:0.12509	eval-mlogloss:0.08914
[116]	train-mlogloss:0.12384	eval-mlogloss:0.08772
[117]	train-mlogloss:0.12252	eval-mlogloss:0.08605
[118]	train-mlogloss:0.12092	eval-mlogloss:0.08443
[119]	train-mlogloss:0.11947	eval-mlogloss:0.08325
[120]	train-mlogloss:0.11797	eval-mlogloss:0.08204
[121]	train-mlogloss:0.11659	eval-mlogloss:0.08047
[122]	train-mlogloss:0.11521	eval-mlogloss:0.07905
[123]	train-mlogloss:0.11378	eval-mlogloss:0.07796
[124]	train-mlogloss:0.11240	eval-mlogloss:0.07684
[125]	train-mlogloss:0.11123	eval-mlogloss:0.07558
[126]	train-mlogloss:0.10988	eval-mlogloss:0.07423
[127]	train-mlogloss:0.10855	eval-mlogloss:0.07303

[I 2026-02-27 06:06:49,184] Trial 7 pruned. Trial was pruned at iteration 128.

[0]	train-mlogloss:0.96983	eval-mlogloss:0.96789
[1]	train-mlogloss:0.81261	eval-mlogloss:0.79911

[I 2026-02-27 06:06:49,203] Trial 8 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03374	eval-mlogloss:1.05017
[1]	train-mlogloss:0.91314	eval-mlogloss:0.92217

[I 2026-02-27 06:06:49,223] Trial 9 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.09277	eval-mlogloss:1.09518
[1]	train-mlogloss:1.07888	eval-mlogloss:1.08067
[2]	train-mlogloss:1.06509	eval-mlogloss:1.06626
[3]	train-mlogloss:1.05483	eval-mlogloss:1.05502
[4]	train-mlogloss:1.04377	eval-mlogloss:1.04316
[5]	train-mlogloss:1.03064	eval-mlogloss:1.02943
[6]	train-mlogloss:1.02069	eval-mlogloss:1.01974
[7]	train-mlogloss:1.01307	eval-mlogloss:1.01258
[8]	train-mlogloss:1.00052	eval-mlogloss:0.99945
[9]	train-mlogloss:0.99101	eval-mlogloss:0.99019
[10]	train-mlogloss:0.97886	eval-mlogloss:0.97780
[11]	train-mlogloss:0.96841	eval-mlogloss:0.96724
[12]	train-mlogloss:0.96398	eval-mlogloss:0.96244
[13]	train-mlogloss:0.95237	eval-mlogloss:0.94995
[14]	train-mlogloss:0.94809	eval-mlogloss:0.94606
[15]	train-mlogloss:0.94133	eval-mlogloss:0.93962
[16]	train-mlogloss:0.93405	eval-mlogloss:0.93220
[17]	train-mlogloss:0.92549	eval-mlogloss:0.92385
[18]	train-mlogloss:0.91894	eval-mlogloss:0.91768
[19]	train-mlogloss:0.91248	eval-mlogloss:0.91157
[20]	train-mlogloss:0.90169	eval-mlogloss:0.90023
[21]	train-mlogloss:0.89414	eval-mlogloss:0.89260
[22]	train-mlogloss:0.88740	eval-mlogloss:0.88616
[23]	train-mlogloss:0.87708	eval-mlogloss:0.87535
[24]	train-mlogloss:0.87118	eval-mlogloss:0.86879
[25]	train-mlogloss:0.86366	eval-mlogloss:0.86040
[26]	train-mlogloss:0.85539	eval-mlogloss:0.85174
[27]	train-mlogloss:0.85296	eval-mlogloss:0.84955
[28]	train-mlogloss:0.84956	eval-mlogloss:0.84678
[29]	train-mlogloss:0.84188	eval-mlogloss:0.83845
[30]	train-mlogloss:0.83455	eval-mlogloss:0.83099
[31]	train-mlogloss:0.83204	eval-mlogloss:0.82920
[32]	train-mlogloss:0.82732	eval-mlogloss:0.82478
[33]	train-mlogloss:0.82297	eval-mlogloss:0.82043
[34]	train-mlogloss:0.81476	eval-mlogloss:0.81204
[35]	train-mlogloss:0.80989	eval-mlogloss:0.80670
[36]	train-mlogloss:0.80580	eval-mlogloss:0.80255
[37]	train-mlogloss:0.79939	eval-mlogloss:0.79629
[38]	train-mlogloss:0.79239	eval-mlogloss:0.78902
[39]	train-mlogloss:0.78702	eval-mlogloss:0.78349
[40]	train-mlogloss:0.78400	eval-mlogloss:0.78100
[41]	train-mlogloss:0.77764	eval-mlogloss:0.77385
[42]	train-mlogloss:0.77549	eval-mlogloss:0.77252
[43]	train-mlogloss:0.76949	eval-mlogloss:0.76622
[44]	train-mlogloss:0.76310	eval-mlogloss:0.75958
[45]	train-mlogloss:0.75947	eval-mlogloss:0.75548
[46]	train-mlogloss:0.75319	eval-mlogloss:0.74906
[47]	train-mlogloss:0.74852	eval-mlogloss:0.74439
[48]	train-mlogloss:0.74189	eval-mlogloss:0.73740
[49]	train-mlogloss:0.73533	eval-mlogloss:0.73050
[50]	train-mlogloss:0.72910	eval-mlogloss:0.72380
[51]	train-mlogloss:0.72532	eval-mlogloss:0.72009
[52]	train-mlogloss:0.72166	eval-mlogloss:0.71664
[53]	train-mlogloss:0.71397	eval-mlogloss:0.70820
[54]	train-mlogloss:0.71033	eval-mlogloss:0.70460
[55]	train-mlogloss:0.70286	eval-mlogloss:0.69677
[56]	train-mlogloss:0.69705	eval-mlogloss:0.69073
[57]	train-mlogloss:0.68972	eval-mlogloss:0.68266
[58]	train-mlogloss:0.68583	eval-mlogloss:0.67911
[59]	train-mlogloss:0.68359	eval-mlogloss:0.67682
[60]	train-mlogloss:0.67835	eval-mlogloss:0.67097
[61]	train-mlogloss:0.67391	eval-mlogloss:0.66640
[62]	train-mlogloss:0.66697	eval-mlogloss:0.65912
[63]	train-mlogloss:0.66327	eval-mlogloss:0.65571
[64]	train-mlogloss:0.66106	eval-mlogloss:0.65366
[65]	train-mlogloss:0.65723	eval-mlogloss:0.64973
[66]	train-mlogloss:0.65201	eval-mlogloss:0.64443
[67]	train-mlogloss:0.64784	eval-mlogloss:0.64033
[68]	train-mlogloss:0.64566	eval-mlogloss:0.63794
[69]	train-mlogloss:0.63912	eval-mlogloss:0.63083
[70]	train-mlogloss:0.63528	eval-mlogloss:0.62665
[71]	train-mlogloss:0.62890	eval-mlogloss:0.61971
[72]	train-mlogloss:0.62397	eval-mlogloss:0.61471
[73]	train-mlogloss:0.62028	eval-mlogloss:0.61071
[74]	train-mlogloss:0.61596	eval-mlogloss:0.60615
[75]	train-mlogloss:0.61058	eval-mlogloss:0.60038
[76]	train-mlogloss:0.60732	eval-mlogloss:0.59735
[77]	train-mlogloss:0.60464	eval-mlogloss:0.59489
[78]	train-mlogloss:0.60181	eval-mlogloss:0.59207
[79]	train-mlogloss:0.59919	eval-mlogloss:0.58969
[80]	train-mlogloss:0.59612	eval-mlogloss:0.58651
[81]	train-mlogloss:0.59160	eval-mlogloss:0.58189
[82]	train-mlogloss:0.58887	eval-mlogloss:0.57917
[83]	train-mlogloss:0.58493	eval-mlogloss:0.57472
[84]	train-mlogloss:0.58170	eval-mlogloss:0.57130
[85]	train-mlogloss:0.57744	eval-mlogloss:0.56682
[86]	train-mlogloss:0.57303	eval-mlogloss:0.56200
[87]	train-mlogloss:0.56875	eval-mlogloss:0.55749
[88]	train-mlogloss:0.56539	eval-mlogloss:0.55367
[89]	train-mlogloss:0.56101	eval-mlogloss:0.54889
[90]	train-mlogloss:0.55707	eval-mlogloss:0.54444
[91]	train-mlogloss:0.55403	eval-mlogloss:0.54134
[92]	train-mlogloss:0.54938	eval-mlogloss:0.53641
[93]	train-mlogloss:0.54778	eval-mlogloss:0.53504
[94]	train-mlogloss:0.54256	eval-mlogloss:0.52912
[95]	train-mlogloss:0.53812	eval-mlogloss:0.52404
[96]	train-mlogloss:0.53306	eval-mlogloss:0.51855
[97]	train-mlogloss:0.53051	eval-mlogloss:0.51614
[98]	train-mlogloss:0.52749	eval-mlogloss:0.51270
[99]	train-mlogloss:0.52655	eval-mlogloss:0.51199
[100]	train-mlogloss:0.52315	eval-mlogloss:0.50848
[101]	train-mlogloss:0.52023	eval-mlogloss:0.50517
[102]	train-mlogloss:0.51797	eval-mlogloss:0.50300
[103]	train-mlogloss:0.51314	eval-mlogloss:0.49773
[104]	train-mlogloss:0.51048	eval-mlogloss:0.49501
[105]	train-mlogloss:0.50797	eval-mlogloss:0.49252
[106]	train-mlogloss:0.50484	eval-mlogloss:0.48907
[107]	train-mlogloss:0.50024	eval-mlogloss:0.48382
[108]	train-mlogloss:0.49786	eval-mlogloss:0.48114
[109]	train-mlogloss:0.49331	eval-mlogloss:0.47602
[110]	train-mlogloss:0.49069	eval-mlogloss:0.47292
[111]	train-mlogloss:0.48716	eval-mlogloss:0.46901
[112]	train-mlogloss:0.48477	eval-mlogloss:0.46650
[113]	train-mlogloss:0.48039	eval-mlogloss:0.46157
[114]	train-mlogloss:0.47812	eval-mlogloss:0.45931
[115]	train-mlogloss:0.47518	eval-mlogloss:0.45616
[116]	train-mlogloss:0.47092	eval-mlogloss:0.45148
[117]	train-mlogloss:0.46763	eval-mlogloss:0.44781
[118]	train-mlogloss:0.46462	eval-mlogloss:0.44458
[119]	train-mlogloss:0.46236	eval-mlogloss:0.44212
[120]	train-mlogloss:0.45830	eval-mlogloss:0.43767
[121]	train-mlogloss:0.45513	eval-mlogloss:0.43427
[122]	train-mlogloss:0.45116	eval-mlogloss:0.42970
[123]	train-mlogloss:0.44771	eval-mlogloss:0.42589
[124]	train-mlogloss:0.44505	eval-mlogloss:0.42305
[125]	train-mlogloss:0.44233	eval-mlogloss:0.41989
[126]	train-mlogloss:0.44029	eval-mlogloss:0.41771
[127]	train-mlogloss:0.43837	eval-mlogloss:0.41559
[128]	train-mlogloss:0.43565	eval-mlogloss:0.41264
[129]	train-mlogloss:0.43393	eval-mlogloss:0.41071
[130]	train-mlogloss:0.43330	eval-mlogloss:0.41046
[131]	train-mlogloss:0.42964	eval-mlogloss:0.40621
[132]	train-mlogloss:0.42680	eval-mlogloss:0.40303
[133]	train-mlogloss:0.42448	eval-mlogloss:0.40040
[134]	train-mlogloss:0.42290	eval-mlogloss:0.39894
[135]	train-mlogloss:0.42030	eval-mlogloss:0.39596
[136]	train-mlogloss:0.41805	eval-mlogloss:0.39342
[137]	train-mlogloss:0.41446	eval-mlogloss:0.38958
[138]	train-mlogloss:0.41203	eval-mlogloss:0.38681
[139]	train-mlogloss:0.41047	eval-mlogloss:0.38543
[140]	train-mlogloss:0.40784	eval-mlogloss:0.38245
[141]	train-mlogloss:0.40535	eval-mlogloss:0.37975
[142]	train-mlogloss:0.40273	eval-mlogloss:0.37692
[143]	train-mlogloss:0.39933	eval-mlogloss:0.37329
[144]	train-mlogloss:0.39652	eval-mlogloss:0.37010
[145]	train-mlogloss:0.39443	eval-mlogloss:0.36772
[146]	train-mlogloss:0.39194	eval-mlogloss:0.36491
[147]	train-mlogloss:0.38978	eval-mlogloss:0.36258
[148]	train-mlogloss:0.38736	eval-mlogloss:0.35984
[149]	train-mlogloss:0.38661	eval-mlogloss:0.35909
[150]	train-mlogloss:0.38351	eval-mlogloss:0.35567
[151]	train-mlogloss:0.38051	eval-mlogloss:0.35214
[152]	train-mlogloss:0.37900	eval-mlogloss:0.35051
[153]	train-mlogloss:0.37690	eval-mlogloss:0.34838
[154]	train-mlogloss:0.37386	eval-mlogloss:0.34515
[155]	train-mlogloss:0.37155	eval-mlogloss:0.34255
[156]	train-mlogloss:0.36960	eval-mlogloss:0.34020
[157]	train-mlogloss:0.36821	eval-mlogloss:0.33867
[158]	train-mlogloss:0.36600	eval-mlogloss:0.33608
[159]	train-mlogloss:0.36470	eval-mlogloss:0.33459
[160]	train-mlogloss:0.36234	eval-mlogloss:0.33186
[161]	train-mlogloss:0.35951	eval-mlogloss:0.32878
[162]	train-mlogloss:0.35830	eval-mlogloss:0.32737
[163]	train-mlogloss:0.35713	eval-mlogloss:0.32600
[164]	train-mlogloss:0.35649	eval-mlogloss:0.32543
[165]	train-mlogloss:0.35524	eval-mlogloss:0.32390
[166]	train-mlogloss:0.35264	eval-mlogloss:0.32088
[167]	train-mlogloss:0.35010	eval-mlogloss:0.31792
[168]	train-mlogloss:0.34826	eval-mlogloss:0.31577
[169]	train-mlogloss:0.34717	eval-mlogloss:0.31467
[170]	train-mlogloss:0.34681	eval-mlogloss:0.31448
[171]	train-mlogloss:0.34511	eval-mlogloss:0.31270
[172]	train-mlogloss:0.34446	eval-mlogloss:0.31212
[173]	train-mlogloss:0.34357	eval-mlogloss:0.31106
[174]	train-mlogloss:0.34216	eval-mlogloss:0.30937
[175]	train-mlogloss:0.34085	eval-mlogloss:0.30802
[176]	train-mlogloss:0.33892	eval-mlogloss:0.30574
[177]	train-mlogloss:0.33812	eval-mlogloss:0.30479
[178]	train-mlogloss:0.33631	eval-mlogloss:0.30282
[179]	train-mlogloss:0.33547	eval-mlogloss:0.30189
[180]	train-mlogloss:0.33383	eval-mlogloss:0.29993
[181]	train-mlogloss:0.33204	eval-mlogloss:0.29799
[182]	train-mlogloss:0.33086	eval-mlogloss:0.29672
[183]	train-mlogloss:0.33032	eval-mlogloss:0.29624
[184]	train-mlogloss:0.32860	eval-mlogloss:0.29440
[185]	train-mlogloss:0.32686	eval-mlogloss:0.29247
[186]	train-mlogloss:0.32517	eval-mlogloss:0.29066
[187]	train-mlogloss:0.32343	eval-mlogloss:0.28875
[188]	train-mlogloss:0.32163	eval-mlogloss:0.28664
[189]	train-mlogloss:0.31937	eval-mlogloss:0.28415
[190]	train-mlogloss:0.31828	eval-mlogloss:0.28302
[191]	train-mlogloss:0.31678	eval-mlogloss:0.28127
[192]	train-mlogloss:0.31553	eval-mlogloss:0.27994
[193]	train-mlogloss:0.31432	eval-mlogloss:0.27847
[194]	train-mlogloss:0.31279	eval-mlogloss:0.27668
[195]	train-mlogloss:0.31070	eval-mlogloss:0.27443
[196]	train-mlogloss:0.30934	eval-mlogloss:0.27305
[197]	train-mlogloss:0.30732	eval-mlogloss:0.27086
[198]	train-mlogloss:0.30629	eval-mlogloss:0.26975
[199]	train-mlogloss:0.30537	eval-mlogloss:0.26866
[200]	train-mlogloss:0.30391	eval-mlogloss:0.26713
[201]	train-mlogloss:0.30295	eval-mlogloss:0.26615
[202]	train-mlogloss:0.30219	eval-mlogloss:0.26549
[203]	train-mlogloss:0.30080	eval-mlogloss:0.26404
[204]	train-mlogloss:0.29985	eval-mlogloss:0.26306
[205]	train-mlogloss:0.29900	eval-mlogloss:0.26204
[206]	train-mlogloss:0.29787	eval-mlogloss:0.26082
[207]	train-mlogloss:0.29679	eval-mlogloss:0.25949
[208]	train-mlogloss:0.29542	eval-mlogloss:0.25801
[209]	train-mlogloss:0.29365	eval-mlogloss:0.25579
[210]	train-mlogloss:0.29318	eval-mlogloss:0.25539
[211]	train-mlogloss:0.29246	eval-mlogloss:0.25470
[212]	train-mlogloss:0.29109	eval-mlogloss:0.25323
[213]	train-mlogloss:0.28958	eval-mlogloss:0.25157
[214]	train-mlogloss:0.28784	eval-mlogloss:0.24952
[215]	train-mlogloss:0.28615	eval-mlogloss:0.24739
[216]	train-mlogloss:0.28551	eval-mlogloss:0.24668
[217]	train-mlogloss:0.28385	eval-mlogloss:0.24458
[218]	train-mlogloss:0.28341	eval-mlogloss:0.24419
[219]	train-mlogloss:0.28171	eval-mlogloss:0.24233
[220]	train-mlogloss:0.28087	eval-mlogloss:0.24138
[221]	train-mlogloss:0.28008	eval-mlogloss:0.24049
[222]	train-mlogloss:0.27932	eval-mlogloss:0.23974
[223]	train-mlogloss:0.27857	eval-mlogloss:0.23893
[224]	train-mlogloss:0.27738	eval-mlogloss:0.23769
[225]	train-mlogloss:0.27691	eval-mlogloss:0.23715
[226]	train-mlogloss:0.27576	eval-mlogloss:0.23571
[227]	train-mlogloss:0.27515	eval-mlogloss:0.23518
[228]	train-mlogloss:0.27443	eval-mlogloss:0.23446
[229]	train-mlogloss:0.27353	eval-mlogloss:0.23349
[230]	train-mlogloss:0.27325	eval-mlogloss:0.23322
[231]	train-mlogloss:0.27213	eval-mlogloss:0.23182
[232]	train-mlogloss:0.27195	eval-mlogloss:0.23178
[233]	train-mlogloss:0.27109	eval-mlogloss:0.23072
[234]	train-mlogloss:0.26957	eval-mlogloss:0.22879
[235]	train-mlogloss:0.26833	eval-mlogloss:0.22716
[236]	train-mlogloss:0.26760	eval-mlogloss:0.22628
[237]	train-mlogloss:0.26650	eval-mlogloss:0.22511
[238]	train-mlogloss:0.26543	eval-mlogloss:0.22377
[239]	train-mlogloss:0.26449	eval-mlogloss:0.22270
[240]	train-mlogloss:0.26309	eval-mlogloss:0.22094
[241]	train-mlogloss:0.26243	eval-mlogloss:0.22029
[242]	train-mlogloss:0.26145	eval-mlogloss:0.21911
[243]	train-mlogloss:0.26085	eval-mlogloss:0.21851
[244]	train-mlogloss:0.26024	eval-mlogloss:0.21796
[245]	train-mlogloss:0.25918	eval-mlogloss:0.21670
[246]	train-mlogloss:0.25861	eval-mlogloss:0.21600
[247]	train-mlogloss:0.25837	eval-mlogloss:0.21577
[248]	train-mlogloss:0.25820	eval-mlogloss:0.21569
[249]	train-mlogloss:0.25712	eval-mlogloss:0.21426
[250]	train-mlogloss:0.25609	eval-mlogloss:0.21303
[251]	train-mlogloss:0.25546	eval-mlogloss:0.21241
[252]	train-mlogloss:0.25485	eval-mlogloss:0.21170
[253]	train-mlogloss:0.25425	eval-mlogloss:0.21095
[254]	train-mlogloss:0.25339	eval-mlogloss:0.20997
[255]	train-mlogloss:0.25293	eval-mlogloss:0.20952
[256]	train-mlogloss:0.25216	eval-mlogloss:0.20869
[257]	train-mlogloss:0.25127	eval-mlogloss:0.20766
[258]	train-mlogloss:0.25055	eval-mlogloss:0.20676
[259]	train-mlogloss:0.25025	eval-mlogloss:0.20651
[260]	train-mlogloss:0.24999	eval-mlogloss:0.20625
[261]	train-mlogloss:0.24909	eval-mlogloss:0.20512
[262]	train-mlogloss:0.24822	eval-mlogloss:0.20420
[263]	train-mlogloss:0.24734	eval-mlogloss:0.20315
[264]	train-mlogloss:0.24723	eval-mlogloss:0.20306
[265]	train-mlogloss:0.24662	eval-mlogloss:0.20238
[266]	train-mlogloss:0.24564	eval-mlogloss:0.20132
[267]	train-mlogloss:0.24503	eval-mlogloss:0.20065
[268]	train-mlogloss:0.24449	eval-mlogloss:0.19996
[269]	train-mlogloss:0.24354	eval-mlogloss:0.19869
[270]	train-mlogloss:0.24258	eval-mlogloss:0.19767
[271]	train-mlogloss:0.24179	eval-mlogloss:0.19690
[272]	train-mlogloss:0.24062	eval-mlogloss:0.19553
[273]	train-mlogloss:0.24004	eval-mlogloss:0.19488
[274]	train-mlogloss:0.23945	eval-mlogloss:0.19422
[275]	train-mlogloss:0.23829	eval-mlogloss:0.19290
[276]	train-mlogloss:0.23774	eval-mlogloss:0.19220
[277]	train-mlogloss:0.23703	eval-mlogloss:0.19141
[278]	train-mlogloss:0.23623	eval-mlogloss:0.19046
[279]	train-mlogloss:0.23530	eval-mlogloss:0.18946
[280]	train-mlogloss:0.23451	eval-mlogloss:0.18855
[281]	train-mlogloss:0.23362	eval-mlogloss:0.18760
[282]	train-mlogloss:0.23274	eval-mlogloss:0.18664
[283]	train-mlogloss:0.23256	eval-mlogloss:0.18647
[284]	train-mlogloss:0.23165	eval-mlogloss:0.18531
[285]	train-mlogloss:0.23127	eval-mlogloss:0.18494
[286]	train-mlogloss:0.23029	eval-mlogloss:0.18384
[287]	train-mlogloss:0.22929	eval-mlogloss:0.18263
[288]	train-mlogloss:0.22876	eval-mlogloss:0.18205
[289]	train-mlogloss:0.22804	eval-mlogloss:0.18124
[290]	train-mlogloss:0.22744	eval-mlogloss:0.18059
[291]	train-mlogloss:0.22664	eval-mlogloss:0.17972
[292]	train-mlogloss:0.22643	eval-mlogloss:0.17951
[293]	train-mlogloss:0.22609	eval-mlogloss:0.17916
[294]	train-mlogloss:0.22510	eval-mlogloss:0.17800
[295]	train-mlogloss:0.22461	eval-mlogloss:0.17739
[296]	train-mlogloss:0.22413	eval-mlogloss:0.17684
[297]	train-mlogloss:0.22362	eval-mlogloss:0.17625
[298]	train-mlogloss:0.22330	eval-mlogloss:0.17586
[299]	train-mlogloss:0.22280	eval-mlogloss:0.17518

[I 2026-02-27 06:06:50,334] Trial 10 finished with value: 1.0 and parameters: {'lambda': 0.7909528238404152, 'alpha': 0.2607153128642381, 'eta': 0.011402145987918506, 'gamma': 0.3157850316447969, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.9911957371258374, 'colsample_bytree': 0.4080733236603174}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.82746	eval-mlogloss:0.80858
[1]	train-mlogloss:0.64643	eval-mlogloss:0.61435

[I 2026-02-27 06:06:50,383] Trial 11 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.78358	eval-mlogloss:0.76254
[1]	train-mlogloss:0.58785	eval-mlogloss:0.55992

[I 2026-02-27 06:06:50,423] Trial 12 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.84403	eval-mlogloss:0.82353
[1]	train-mlogloss:0.66845	eval-mlogloss:0.63288

[I 2026-02-27 06:06:50,478] Trial 13 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.93343	eval-mlogloss:0.94205
[1]	train-mlogloss:0.75641	eval-mlogloss:0.75536

[I 2026-02-27 06:06:50,521] Trial 14 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03651	eval-mlogloss:1.03679
[1]	train-mlogloss:0.94931	eval-mlogloss:0.94552

[I 2026-02-27 06:06:50,562] Trial 15 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.90380	eval-mlogloss:0.88998
[1]	train-mlogloss:0.68315	eval-mlogloss:0.65310

[I 2026-02-27 06:06:50,622] Trial 16 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.91529	eval-mlogloss:0.89777
[1]	train-mlogloss:0.77319	eval-mlogloss:0.74804

[I 2026-02-27 06:06:50,662] Trial 17 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.93682	eval-mlogloss:0.93952
[1]	train-mlogloss:0.76404	eval-mlogloss:0.75676

[I 2026-02-27 06:06:50,713] Trial 18 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03031	eval-mlogloss:1.02625
[1]	train-mlogloss:0.96863	eval-mlogloss:0.96103
[2]	train-mlogloss:0.91154	eval-mlogloss:0.90150
[3]	train-mlogloss:0.85764	eval-mlogloss:0.84495
[4]	train-mlogloss:0.81052	eval-mlogloss:0.79572
[5]	train-mlogloss:0.76469	eval-mlogloss:0.74580
[6]	train-mlogloss:0.72385	eval-mlogloss:0.70244
[7]	train-mlogloss:0.68653	eval-mlogloss:0.66393

[I 2026-02-27 06:06:50,796] Trial 19 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.99151	eval-mlogloss:0.99057
[1]	train-mlogloss:0.86830	eval-mlogloss:0.86125

[I 2026-02-27 06:06:50,845] Trial 20 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98019	eval-mlogloss:0.97203
[1]	train-mlogloss:0.88042	eval-mlogloss:0.86681

[I 2026-02-27 06:06:51,357] Trial 21 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.02251	eval-mlogloss:1.01861
[1]	train-mlogloss:0.95522	eval-mlogloss:0.94748
[2]	train-mlogloss:0.89319	eval-mlogloss:0.88078
[3]	train-mlogloss:0.83565	eval-mlogloss:0.82068
[4]	train-mlogloss:0.78487	eval-mlogloss:0.76762
[5]	train-mlogloss:0.73750	eval-mlogloss:0.71614
[6]	train-mlogloss:0.69445	eval-mlogloss:0.67067
[7]	train-mlogloss:0.65498	eval-mlogloss:0.62995

[I 2026-02-27 06:06:51,577] Trial 22 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.05613	eval-mlogloss:1.05461
[1]	train-mlogloss:1.01663	eval-mlogloss:1.01432
[2]	train-mlogloss:0.97863	eval-mlogloss:0.97462
[3]	train-mlogloss:0.94211	eval-mlogloss:0.93651
[4]	train-mlogloss:0.90850	eval-mlogloss:0.90153
[5]	train-mlogloss:0.87566	eval-mlogloss:0.86617
[6]	train-mlogloss:0.84537	eval-mlogloss:0.83390
[7]	train-mlogloss:0.81640	eval-mlogloss:0.80425

[I 2026-02-27 06:06:51,689] Trial 23 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.03090	eval-mlogloss:1.02947
[1]	train-mlogloss:0.93756	eval-mlogloss:0.93198

[I 2026-02-27 06:06:51,732] Trial 24 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.95042	eval-mlogloss:0.94176
[1]	train-mlogloss:0.83079	eval-mlogloss:0.81539

[I 2026-02-27 06:06:51,762] Trial 25 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.80428	eval-mlogloss:0.77771
[1]	train-mlogloss:0.61373	eval-mlogloss:0.57123

[I 2026-02-27 06:06:51,985] Trial 26 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04652	eval-mlogloss:1.04409
[1]	train-mlogloss:0.99827	eval-mlogloss:0.99488
[2]	train-mlogloss:0.95303	eval-mlogloss:0.94751
[3]	train-mlogloss:0.91058	eval-mlogloss:0.90390
[4]	train-mlogloss:0.87078	eval-mlogloss:0.86240
[5]	train-mlogloss:0.83357	eval-mlogloss:0.82349
[6]	train-mlogloss:0.79867	eval-mlogloss:0.78752
[7]	train-mlogloss:0.76590	eval-mlogloss:0.75369

[I 2026-02-27 06:06:52,024] Trial 27 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:0.87343	eval-mlogloss:0.86380
[1]	train-mlogloss:0.70988	eval-mlogloss:0.69635

[I 2026-02-27 06:06:52,056] Trial 28 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.96708	eval-mlogloss:0.97570
[1]	train-mlogloss:0.71300	eval-mlogloss:0.70276

[I 2026-02-27 06:06:52,081] Trial 29 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03426	eval-mlogloss:1.03471
[1]	train-mlogloss:0.94557	eval-mlogloss:0.94222

[I 2026-02-27 06:06:52,105] Trial 30 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.09183	eval-mlogloss:1.09445
[1]	train-mlogloss:1.07558	eval-mlogloss:1.07749
[2]	train-mlogloss:1.05948	eval-mlogloss:1.06065
[3]	train-mlogloss:1.04757	eval-mlogloss:1.04759
[4]	train-mlogloss:1.03474	eval-mlogloss:1.03382
[5]	train-mlogloss:1.01954	eval-mlogloss:1.01792
[6]	train-mlogloss:1.00808	eval-mlogloss:1.00677
[7]	train-mlogloss:0.99929	eval-mlogloss:0.99851
[8]	train-mlogloss:0.98485	eval-mlogloss:0.98339
[9]	train-mlogloss:0.97397	eval-mlogloss:0.97279
[10]	train-mlogloss:0.96009	eval-mlogloss:0.95863
[11]	train-mlogloss:0.94817	eval-mlogloss:0.94659
[12]	train-mlogloss:0.94314	eval-mlogloss:0.94113
[13]	train-mlogloss:0.92995	eval-mlogloss:0.92693
[14]	train-mlogloss:0.92512	eval-mlogloss:0.92308
[15]	train-mlogloss:0.91750	eval-mlogloss:0.91579
[16]	train-mlogloss:0.90930	eval-mlogloss:0.90796
[17]	train-mlogloss:0.89967	eval-mlogloss:0.89858
[18]	train-mlogloss:0.89238	eval-mlogloss:0.89158
[19]	train-mlogloss:0.88518	eval-mlogloss:0.88467
[20]	train-mlogloss:0.87306	eval-mlogloss:0.87192
[21]	train-mlogloss:0.86468	eval-mlogloss:0.86334
[22]	train-mlogloss:0.85717	eval-mlogloss:0.85616
[23]	train-mlogloss:0.84569	eval-mlogloss:0.84405
[24]	train-mlogloss:0.83916	eval-mlogloss:0.83677
[25]	train-mlogloss:0.83079	eval-mlogloss:0.82753
[26]	train-mlogloss:0.82163	eval-mlogloss:0.81792
[27]	train-mlogloss:0.81901	eval-mlogloss:0.81533
[28]	train-mlogloss:0.81529	eval-mlogloss:0.81229
[29]	train-mlogloss:0.80677	eval-mlogloss:0.80302
[30]	train-mlogloss:0.79869	eval-mlogloss:0.79479
[31]	train-mlogloss:0.79601	eval-mlogloss:0.79281

[I 2026-02-27 06:06:52,183] Trial 31 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.09292	eval-mlogloss:1.09570
[1]	train-mlogloss:1.07909	eval-mlogloss:1.08125
[2]	train-mlogloss:1.06560	eval-mlogloss:1.06729
[3]	train-mlogloss:1.05554	eval-mlogloss:1.05623
[4]	train-mlogloss:1.04465	eval-mlogloss:1.04464
[5]	train-mlogloss:1.03170	eval-mlogloss:1.03105
[6]	train-mlogloss:1.02184	eval-mlogloss:1.02137
[7]	train-mlogloss:1.01410	eval-mlogloss:1.01408
[8]	train-mlogloss:1.00170	eval-mlogloss:1.00106
[9]	train-mlogloss:0.99227	eval-mlogloss:0.99181
[10]	train-mlogloss:0.98019	eval-mlogloss:0.97938
[11]	train-mlogloss:0.96966	eval-mlogloss:0.96865
[12]	train-mlogloss:0.96525	eval-mlogloss:0.96370
[13]	train-mlogloss:0.95386	eval-mlogloss:0.95141
[14]	train-mlogloss:0.94962	eval-mlogloss:0.94789
[15]	train-mlogloss:0.94285	eval-mlogloss:0.94127
[16]	train-mlogloss:0.93561	eval-mlogloss:0.93407
[17]	train-mlogloss:0.92712	eval-mlogloss:0.92576
[18]	train-mlogloss:0.92058	eval-mlogloss:0.91954
[19]	train-mlogloss:0.91409	eval-mlogloss:0.91337
[20]	train-mlogloss:0.90342	eval-mlogloss:0.90209
[21]	train-mlogloss:0.89591	eval-mlogloss:0.89463
[22]	train-mlogloss:0.88923	eval-mlogloss:0.88821
[23]	train-mlogloss:0.87907	eval-mlogloss:0.87747
[24]	train-mlogloss:0.87317	eval-mlogloss:0.87105
[25]	train-mlogloss:0.86567	eval-mlogloss:0.86268
[26]	train-mlogloss:0.85741	eval-mlogloss:0.85415
[27]	train-mlogloss:0.85493	eval-mlogloss:0.85220
[28]	train-mlogloss:0.85138	eval-mlogloss:0.84936
[29]	train-mlogloss:0.84377	eval-mlogloss:0.84104
[30]	train-mlogloss:0.83656	eval-mlogloss:0.83335
[31]	train-mlogloss:0.83406	eval-mlogloss:0.83166
[32]	train-mlogloss:0.82921	eval-mlogloss:0.82719
[33]	train-mlogloss:0.82484	eval-mlogloss:0.82304
[34]	train-mlogloss:0.81668	eval-mlogloss:0.81454
[35]	train-mlogloss:0.81189	eval-mlogloss:0.80920
[36]	train-mlogloss:0.80772	eval-mlogloss:0.80521
[37]	train-mlogloss:0.80143	eval-mlogloss:0.79902
[38]	train-mlogloss:0.79445	eval-mlogloss:0.79186
[39]	train-mlogloss:0.78913	eval-mlogloss:0.78647
[40]	train-mlogloss:0.78628	eval-mlogloss:0.78389
[41]	train-mlogloss:0.78002	eval-mlogloss:0.77685
[42]	train-mlogloss:0.77782	eval-mlogloss:0.77537
[43]	train-mlogloss:0.77182	eval-mlogloss:0.76900
[44]	train-mlogloss:0.76543	eval-mlogloss:0.76236
[45]	train-mlogloss:0.76181	eval-mlogloss:0.75836
[46]	train-mlogloss:0.75555	eval-mlogloss:0.75193
[47]	train-mlogloss:0.75091	eval-mlogloss:0.74726
[48]	train-mlogloss:0.74430	eval-mlogloss:0.74036
[49]	train-mlogloss:0.73772	eval-mlogloss:0.73354
[50]	train-mlogloss:0.73153	eval-mlogloss:0.72677
[51]	train-mlogloss:0.72778	eval-mlogloss:0.72315
[52]	train-mlogloss:0.72400	eval-mlogloss:0.71953
[53]	train-mlogloss:0.71642	eval-mlogloss:0.71122
[54]	train-mlogloss:0.71284	eval-mlogloss:0.70752
[55]	train-mlogloss:0.70530	eval-mlogloss:0.69968
[56]	train-mlogloss:0.69950	eval-mlogloss:0.69368
[57]	train-mlogloss:0.69227	eval-mlogloss:0.68575
[58]	train-mlogloss:0.68833	eval-mlogloss:0.68211
[59]	train-mlogloss:0.68604	eval-mlogloss:0.67967
[60]	train-mlogloss:0.68089	eval-mlogloss:0.67393
[61]	train-mlogloss:0.67649	eval-mlogloss:0.66915
[62]	train-mlogloss:0.66944	eval-mlogloss:0.66194
[63]	train-mlogloss:0.66569	eval-mlogloss:0.65838
[64]	train-mlogloss:0.66351	eval-mlogloss:0.65638
[65]	train-mlogloss:0.65969	eval-mlogloss:0.65270
[66]	train-mlogloss:0.65450	eval-mlogloss:0.64742
[67]	train-mlogloss:0.65030	eval-mlogloss:0.64324
[68]	train-mlogloss:0.64813	eval-mlogloss:0.64084
[69]	train-mlogloss:0.64170	eval-mlogloss:0.63388
[70]	train-mlogloss:0.63784	eval-mlogloss:0.62971
[71]	train-mlogloss:0.63142	eval-mlogloss:0.62284
[72]	train-mlogloss:0.62648	eval-mlogloss:0.61779
[73]	train-mlogloss:0.62277	eval-mlogloss:0.61395
[74]	train-mlogloss:0.61850	eval-mlogloss:0.60946
[75]	train-mlogloss:0.61318	eval-mlogloss:0.60372
[76]	train-mlogloss:0.60994	eval-mlogloss:0.60072
[77]	train-mlogloss:0.60730	eval-mlogloss:0.59830
[78]	train-mlogloss:0.60441	eval-mlogloss:0.59535
[79]	train-mlogloss:0.60183	eval-mlogloss:0.59300
[80]	train-mlogloss:0.59880	eval-mlogloss:0.58972
[81]	train-mlogloss:0.59427	eval-mlogloss:0.58493
[82]	train-mlogloss:0.59157	eval-mlogloss:0.58219
[83]	train-mlogloss:0.58768	eval-mlogloss:0.57785
[84]	train-mlogloss:0.58447	eval-mlogloss:0.57446
[85]	train-mlogloss:0.58031	eval-mlogloss:0.57012
[86]	train-mlogloss:0.57593	eval-mlogloss:0.56533
[87]	train-mlogloss:0.57170	eval-mlogloss:0.56065
[88]	train-mlogloss:0.56830	eval-mlogloss:0.55679
[89]	train-mlogloss:0.56393	eval-mlogloss:0.55220
[90]	train-mlogloss:0.56004	eval-mlogloss:0.54785
[91]	train-mlogloss:0.55699	eval-mlogloss:0.54480
[92]	train-mlogloss:0.55229	eval-mlogloss:0.53984
[93]	train-mlogloss:0.55057	eval-mlogloss:0.53829
[94]	train-mlogloss:0.54541	eval-mlogloss:0.53245
[95]	train-mlogloss:0.54096	eval-mlogloss:0.52746
[96]	train-mlogloss:0.53587	eval-mlogloss:0.52190
[97]	train-mlogloss:0.53328	eval-mlogloss:0.51924
[98]	train-mlogloss:0.53032	eval-mlogloss:0.51588
[99]	train-mlogloss:0.52929	eval-mlogloss:0.51520
[100]	train-mlogloss:0.52588	eval-mlogloss:0.51169
[101]	train-mlogloss:0.52297	eval-mlogloss:0.50839
[102]	train-mlogloss:0.52070	eval-mlogloss:0.50610
[103]	train-mlogloss:0.51586	eval-mlogloss:0.50081
[104]	train-mlogloss:0.51313	eval-mlogloss:0.49797
[105]	train-mlogloss:0.51058	eval-mlogloss:0.49541
[106]	train-mlogloss:0.50750	eval-mlogloss:0.49201
[107]	train-mlogloss:0.50296	eval-mlogloss:0.48685
[108]	train-mlogloss:0.50052	eval-mlogloss:0.48414
[109]	train-mlogloss:0.49605	eval-mlogloss:0.47916
[110]	train-mlogloss:0.49341	eval-mlogloss:0.47611
[111]	train-mlogloss:0.48984	eval-mlogloss:0.47221
[112]	train-mlogloss:0.48742	eval-mlogloss:0.46973
[113]	train-mlogloss:0.48297	eval-mlogloss:0.46474
[114]	train-mlogloss:0.48070	eval-mlogloss:0.46238
[115]	train-mlogloss:0.47774	eval-mlogloss:0.45925
[116]	train-mlogloss:0.47358	eval-mlogloss:0.45474
[117]	train-mlogloss:0.47031	eval-mlogloss:0.45111
[118]	train-mlogloss:0.46727	eval-mlogloss:0.44785
[119]	train-mlogloss:0.46502	eval-mlogloss:0.44541
[120]	train-mlogloss:0.46093	eval-mlogloss:0.44093
[121]	train-mlogloss:0.45774	eval-mlogloss:0.43747
[122]	train-mlogloss:0.45372	eval-mlogloss:0.43285
[123]	train-mlogloss:0.45032	eval-mlogloss:0.42912
[124]	train-mlogloss:0.44766	eval-mlogloss:0.42624
[125]	train-mlogloss:0.44495	eval-mlogloss:0.42320
[126]	train-mlogloss:0.44283	eval-mlogloss:0.42092
[127]	train-mlogloss:0.44086	eval-mlogloss:0.41878
[128]	train-mlogloss:0.43812	eval-mlogloss:0.41582
[129]	train-mlogloss:0.43630	eval-mlogloss:0.41380
[130]	train-mlogloss:0.43558	eval-mlogloss:0.41341
[131]	train-mlogloss:0.43183	eval-mlogloss:0.40906
[132]	train-mlogloss:0.42894	eval-mlogloss:0.40582
[133]	train-mlogloss:0.42657	eval-mlogloss:0.40315
[134]	train-mlogloss:0.42500	eval-mlogloss:0.40151
[135]	train-mlogloss:0.42228	eval-mlogloss:0.39837
[136]	train-mlogloss:0.42007	eval-mlogloss:0.39587
[137]	train-mlogloss:0.41654	eval-mlogloss:0.39212
[138]	train-mlogloss:0.41400	eval-mlogloss:0.38945
[139]	train-mlogloss:0.41243	eval-mlogloss:0.38806
[140]	train-mlogloss:0.40979	eval-mlogloss:0.38509
[141]	train-mlogloss:0.40731	eval-mlogloss:0.38242
[142]	train-mlogloss:0.40464	eval-mlogloss:0.37948
[143]	train-mlogloss:0.40127	eval-mlogloss:0.37590
[144]	train-mlogloss:0.39844	eval-mlogloss:0.37279
[145]	train-mlogloss:0.39636	eval-mlogloss:0.37043
[146]	train-mlogloss:0.39393	eval-mlogloss:0.36766
[147]	train-mlogloss:0.39176	eval-mlogloss:0.36535
[148]	train-mlogloss:0.38934	eval-mlogloss:0.36262
[149]	train-mlogloss:0.38861	eval-mlogloss:0.36193
[150]	train-mlogloss:0.38547	eval-mlogloss:0.35843
[151]	train-mlogloss:0.38235	eval-mlogloss:0.35485
[152]	train-mlogloss:0.38084	eval-mlogloss:0.35324
[153]	train-mlogloss:0.37879	eval-mlogloss:0.35111
[154]	train-mlogloss:0.37568	eval-mlogloss:0.34780
[155]	train-mlogloss:0.37339	eval-mlogloss:0.34524
[156]	train-mlogloss:0.37113	eval-mlogloss:0.34273
[157]	train-mlogloss:0.36967	eval-mlogloss:0.34116
[158]	train-mlogloss:0.36716	eval-mlogloss:0.33836
[159]	train-mlogloss:0.36578	eval-mlogloss:0.33687
[160]	train-mlogloss:0.36332	eval-mlogloss:0.33416
[161]	train-mlogloss:0.36047	eval-mlogloss:0.33110
[162]	train-mlogloss:0.35901	eval-mlogloss:0.32953
[163]	train-mlogloss:0.35785	eval-mlogloss:0.32819
[164]	train-mlogloss:0.35725	eval-mlogloss:0.32773
[165]	train-mlogloss:0.35598	eval-mlogloss:0.32620
[166]	train-mlogloss:0.35324	eval-mlogloss:0.32311
[167]	train-mlogloss:0.35055	eval-mlogloss:0.32015
[168]	train-mlogloss:0.34866	eval-mlogloss:0.31802
[169]	train-mlogloss:0.34759	eval-mlogloss:0.31698
[170]	train-mlogloss:0.34719	eval-mlogloss:0.31676
[171]	train-mlogloss:0.34535	eval-mlogloss:0.31492
[172]	train-mlogloss:0.34472	eval-mlogloss:0.31437
[173]	train-mlogloss:0.34383	eval-mlogloss:0.31341
[174]	train-mlogloss:0.34236	eval-mlogloss:0.31172
[175]	train-mlogloss:0.34097	eval-mlogloss:0.31033
[176]	train-mlogloss:0.33876	eval-mlogloss:0.30785
[177]	train-mlogloss:0.33792	eval-mlogloss:0.30695
[178]	train-mlogloss:0.33612	eval-mlogloss:0.30499
[179]	train-mlogloss:0.33527	eval-mlogloss:0.30406
[180]	train-mlogloss:0.33360	eval-mlogloss:0.30213
[181]	train-mlogloss:0.33182	eval-mlogloss:0.30021
[182]	train-mlogloss:0.33064	eval-mlogloss:0.29893
[183]	train-mlogloss:0.33008	eval-mlogloss:0.29845
[184]	train-mlogloss:0.32833	eval-mlogloss:0.29658
[185]	train-mlogloss:0.32658	eval-mlogloss:0.29475
[186]	train-mlogloss:0.32485	eval-mlogloss:0.29289
[187]	train-mlogloss:0.32312	eval-mlogloss:0.29099
[188]	train-mlogloss:0.32123	eval-mlogloss:0.28879
[189]	train-mlogloss:0.31886	eval-mlogloss:0.28629
[190]	train-mlogloss:0.31774	eval-mlogloss:0.28511
[191]	train-mlogloss:0.31621	eval-mlogloss:0.28327
[192]	train-mlogloss:0.31493	eval-mlogloss:0.28190
[193]	train-mlogloss:0.31369	eval-mlogloss:0.28040
[194]	train-mlogloss:0.31212	eval-mlogloss:0.27864
[195]	train-mlogloss:0.30998	eval-mlogloss:0.27630
[196]	train-mlogloss:0.30856	eval-mlogloss:0.27484
[197]	train-mlogloss:0.30646	eval-mlogloss:0.27253
[198]	train-mlogloss:0.30547	eval-mlogloss:0.27152
[199]	train-mlogloss:0.30454	eval-mlogloss:0.27045
[200]	train-mlogloss:0.30304	eval-mlogloss:0.26885
[201]	train-mlogloss:0.30210	eval-mlogloss:0.26790
[202]	train-mlogloss:0.30128	eval-mlogloss:0.26713
[203]	train-mlogloss:0.29980	eval-mlogloss:0.26553
[204]	train-mlogloss:0.29886	eval-mlogloss:0.26457
[205]	train-mlogloss:0.29796	eval-mlogloss:0.26350
[206]	train-mlogloss:0.29682	eval-mlogloss:0.26227
[207]	train-mlogloss:0.29573	eval-mlogloss:0.26094
[208]	train-mlogloss:0.29429	eval-mlogloss:0.25940
[209]	train-mlogloss:0.29248	eval-mlogloss:0.25721
[210]	train-mlogloss:0.29200	eval-mlogloss:0.25679
[211]	train-mlogloss:0.29123	eval-mlogloss:0.25608
[212]	train-mlogloss:0.28983	eval-mlogloss:0.25457
[213]	train-mlogloss:0.28823	eval-mlogloss:0.25281
[214]	train-mlogloss:0.28646	eval-mlogloss:0.25074
[215]	train-mlogloss:0.28479	eval-mlogloss:0.24864
[216]	train-mlogloss:0.28414	eval-mlogloss:0.24793
[217]	train-mlogloss:0.28244	eval-mlogloss:0.24578
[218]	train-mlogloss:0.28200	eval-mlogloss:0.24540
[219]	train-mlogloss:0.28017	eval-mlogloss:0.24342
[220]	train-mlogloss:0.27933	eval-mlogloss:0.24257
[221]	train-mlogloss:0.27855	eval-mlogloss:0.24170
[222]	train-mlogloss:0.27776	eval-mlogloss:0.24097
[223]	train-mlogloss:0.27693	eval-mlogloss:0.24014
[224]	train-mlogloss:0.27568	eval-mlogloss:0.23889
[225]	train-mlogloss:0.27517	eval-mlogloss:0.23832
[226]	train-mlogloss:0.27404	eval-mlogloss:0.23691
[227]	train-mlogloss:0.27340	eval-mlogloss:0.23637
[228]	train-mlogloss:0.27261	eval-mlogloss:0.23556
[229]	train-mlogloss:0.27156	eval-mlogloss:0.23442
[230]	train-mlogloss:0.27123	eval-mlogloss:0.23409
[231]	train-mlogloss:0.27011	eval-mlogloss:0.23270
[232]	train-mlogloss:0.26991	eval-mlogloss:0.23267
[233]	train-mlogloss:0.26895	eval-mlogloss:0.23147
[234]	train-mlogloss:0.26742	eval-mlogloss:0.22953
[235]	train-mlogloss:0.26617	eval-mlogloss:0.22787
[236]	train-mlogloss:0.26544	eval-mlogloss:0.22701
[237]	train-mlogloss:0.26435	eval-mlogloss:0.22580
[238]	train-mlogloss:0.26331	eval-mlogloss:0.22453
[239]	train-mlogloss:0.26233	eval-mlogloss:0.22342
[240]	train-mlogloss:0.26089	eval-mlogloss:0.22158
[241]	train-mlogloss:0.26022	eval-mlogloss:0.22092
[242]	train-mlogloss:0.25919	eval-mlogloss:0.21972
[243]	train-mlogloss:0.25852	eval-mlogloss:0.21902
[244]	train-mlogloss:0.25791	eval-mlogloss:0.21849
[245]	train-mlogloss:0.25680	eval-mlogloss:0.21716
[246]	train-mlogloss:0.25623	eval-mlogloss:0.21646
[247]	train-mlogloss:0.25600	eval-mlogloss:0.21620
[248]	train-mlogloss:0.25586	eval-mlogloss:0.21608
[249]	train-mlogloss:0.25473	eval-mlogloss:0.21457
[250]	train-mlogloss:0.25366	eval-mlogloss:0.21330
[251]	train-mlogloss:0.25297	eval-mlogloss:0.21250
[252]	train-mlogloss:0.25233	eval-mlogloss:0.21174
[253]	train-mlogloss:0.25174	eval-mlogloss:0.21101
[254]	train-mlogloss:0.25089	eval-mlogloss:0.20997
[255]	train-mlogloss:0.25037	eval-mlogloss:0.20955
[256]	train-mlogloss:0.24961	eval-mlogloss:0.20873
[257]	train-mlogloss:0.24870	eval-mlogloss:0.20767
[258]	train-mlogloss:0.24799	eval-mlogloss:0.20678
[259]	train-mlogloss:0.24769	eval-mlogloss:0.20654
[260]	train-mlogloss:0.24738	eval-mlogloss:0.20630
[261]	train-mlogloss:0.24645	eval-mlogloss:0.20513
[262]	train-mlogloss:0.24549	eval-mlogloss:0.20414
[263]	train-mlogloss:0.24455	eval-mlogloss:0.20302
[264]	train-mlogloss:0.24440	eval-mlogloss:0.20292
[265]	train-mlogloss:0.24381	eval-mlogloss:0.20227
[266]	train-mlogloss:0.24283	eval-mlogloss:0.20123
[267]	train-mlogloss:0.24224	eval-mlogloss:0.20057
[268]	train-mlogloss:0.24170	eval-mlogloss:0.19994
[269]	train-mlogloss:0.24073	eval-mlogloss:0.19863
[270]	train-mlogloss:0.23978	eval-mlogloss:0.19762
[271]	train-mlogloss:0.23895	eval-mlogloss:0.19676
[272]	train-mlogloss:0.23773	eval-mlogloss:0.19532
[273]	train-mlogloss:0.23717	eval-mlogloss:0.19470
[274]	train-mlogloss:0.23659	eval-mlogloss:0.19405
[275]	train-mlogloss:0.23537	eval-mlogloss:0.19260
[276]	train-mlogloss:0.23480	eval-mlogloss:0.19185
[277]	train-mlogloss:0.23402	eval-mlogloss:0.19096
[278]	train-mlogloss:0.23324	eval-mlogloss:0.19002
[279]	train-mlogloss:0.23227	eval-mlogloss:0.18898
[280]	train-mlogloss:0.23146	eval-mlogloss:0.18806
[281]	train-mlogloss:0.23058	eval-mlogloss:0.18712
[282]	train-mlogloss:0.22968	eval-mlogloss:0.18611
[283]	train-mlogloss:0.22949	eval-mlogloss:0.18590
[284]	train-mlogloss:0.22847	eval-mlogloss:0.18465
[285]	train-mlogloss:0.22798	eval-mlogloss:0.18422
[286]	train-mlogloss:0.22685	eval-mlogloss:0.18304
[287]	train-mlogloss:0.22579	eval-mlogloss:0.18169
[288]	train-mlogloss:0.22529	eval-mlogloss:0.18114
[289]	train-mlogloss:0.22456	eval-mlogloss:0.18035
[290]	train-mlogloss:0.22392	eval-mlogloss:0.17966
[291]	train-mlogloss:0.22308	eval-mlogloss:0.17876
[292]	train-mlogloss:0.22283	eval-mlogloss:0.17858
[293]	train-mlogloss:0.22245	eval-mlogloss:0.17828
[294]	train-mlogloss:0.22140	eval-mlogloss:0.17716
[295]	train-mlogloss:0.22093	eval-mlogloss:0.17656
[296]	train-mlogloss:0.22045	eval-mlogloss:0.17604
[297]	train-mlogloss:0.21941	eval-mlogloss:0.17493
[298]	train-mlogloss:0.21904	eval-mlogloss:0.17444
[299]	train-mlogloss:0.21804	eval-mlogloss:0.17327

[I 2026-02-27 06:06:53,065] Trial 32 finished with value: 1.0 and parameters: {'lambda': 0.05376188923982205, 'alpha': 0.3432225067462898, 'eta': 0.010853595221062759, 'gamma': 0.2832687662129136, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.95837262930844, 'colsample_bytree': 0.40007148645543844}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.08365	eval-mlogloss:1.08643
[1]	train-mlogloss:1.04809	eval-mlogloss:1.04928
[2]	train-mlogloss:1.01415	eval-mlogloss:1.01336
[3]	train-mlogloss:0.98951	eval-mlogloss:0.98606
[4]	train-mlogloss:0.96336	eval-mlogloss:0.95797
[5]	train-mlogloss:0.93336	eval-mlogloss:0.92621
[6]	train-mlogloss:0.91100	eval-mlogloss:0.90394
[7]	train-mlogloss:0.89425	eval-mlogloss:0.88752

[I 2026-02-27 06:06:53,119] Trial 33 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.05883	eval-mlogloss:1.06093
[1]	train-mlogloss:1.00372	eval-mlogloss:1.00303
[2]	train-mlogloss:0.95240	eval-mlogloss:0.94943
[3]	train-mlogloss:0.90421	eval-mlogloss:0.89936
[4]	train-mlogloss:0.86001	eval-mlogloss:0.85288
[5]	train-mlogloss:0.81782	eval-mlogloss:0.80794
[6]	train-mlogloss:0.77952	eval-mlogloss:0.76850
[7]	train-mlogloss:0.74454	eval-mlogloss:0.73255

[I 2026-02-27 06:06:53,164] Trial 34 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.06570	eval-mlogloss:1.07062
[1]	train-mlogloss:0.98719	eval-mlogloss:0.98848

[I 2026-02-27 06:06:53,203] Trial 35 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.98493	eval-mlogloss:0.98923
[1]	train-mlogloss:0.85390	eval-mlogloss:0.85191

[I 2026-02-27 06:06:53,234] Trial 36 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04011	eval-mlogloss:1.04867
[1]	train-mlogloss:0.92105	eval-mlogloss:0.92332

[I 2026-02-27 06:06:53,286] Trial 37 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:0.93873	eval-mlogloss:0.93519
[1]	train-mlogloss:0.74913	eval-mlogloss:0.73565

[I 2026-02-27 06:06:53,319] Trial 38 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06882	eval-mlogloss:1.06909
[1]	train-mlogloss:1.04347	eval-mlogloss:1.04121
[2]	train-mlogloss:1.01543	eval-mlogloss:1.01146
[3]	train-mlogloss:0.98679	eval-mlogloss:0.98159
[4]	train-mlogloss:0.96166	eval-mlogloss:0.95534
[5]	train-mlogloss:0.93561	eval-mlogloss:0.92792
[6]	train-mlogloss:0.91088	eval-mlogloss:0.90155
[7]	train-mlogloss:0.89068	eval-mlogloss:0.88279

[I 2026-02-27 06:06:53,371] Trial 39 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.01418	eval-mlogloss:1.01666
[1]	train-mlogloss:0.91777	eval-mlogloss:0.91529

[I 2026-02-27 06:06:53,531] Trial 40 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.09194	eval-mlogloss:1.09473
[1]	train-mlogloss:1.07600	eval-mlogloss:1.07808
[2]	train-mlogloss:1.06040	eval-mlogloss:1.06194
[3]	train-mlogloss:1.04887	eval-mlogloss:1.04924
[4]	train-mlogloss:1.03634	eval-mlogloss:1.03594
[5]	train-mlogloss:1.02161	eval-mlogloss:1.02048
[6]	train-mlogloss:1.01041	eval-mlogloss:1.00948
[7]	train-mlogloss:1.00162	eval-mlogloss:1.00123
[8]	train-mlogloss:0.98760	eval-mlogloss:0.98648
[9]	train-mlogloss:0.97694	eval-mlogloss:0.97605
[10]	train-mlogloss:0.96333	eval-mlogloss:0.96204
[11]	train-mlogloss:0.95148	eval-mlogloss:0.94995
[12]	train-mlogloss:0.94634	eval-mlogloss:0.94443
[13]	train-mlogloss:0.93353	eval-mlogloss:0.93063
[14]	train-mlogloss:0.92879	eval-mlogloss:0.92672
[15]	train-mlogloss:0.92120	eval-mlogloss:0.91929
[16]	train-mlogloss:0.91305	eval-mlogloss:0.91104
[17]	train-mlogloss:0.90357	eval-mlogloss:0.90164
[18]	train-mlogloss:0.89627	eval-mlogloss:0.89471
[19]	train-mlogloss:0.88906	eval-mlogloss:0.88787
[20]	train-mlogloss:0.87723	eval-mlogloss:0.87534
[21]	train-mlogloss:0.86882	eval-mlogloss:0.86709
[22]	train-mlogloss:0.86138	eval-mlogloss:0.85983
[23]	train-mlogloss:0.85013	eval-mlogloss:0.84797
[24]	train-mlogloss:0.84361	eval-mlogloss:0.84085
[25]	train-mlogloss:0.83531	eval-mlogloss:0.83161
[26]	train-mlogloss:0.82626	eval-mlogloss:0.82224
[27]	train-mlogloss:0.82349	eval-mlogloss:0.82012
[28]	train-mlogloss:0.81972	eval-mlogloss:0.81692
[29]	train-mlogloss:0.81129	eval-mlogloss:0.80776
[30]	train-mlogloss:0.80340	eval-mlogloss:0.79953
[31]	train-mlogloss:0.80064	eval-mlogloss:0.79772

[I 2026-02-27 06:06:53,646] Trial 41 pruned. Trial was pruned at iteration 32.

[0]	train-mlogloss:1.09298	eval-mlogloss:1.09574
[1]	train-mlogloss:1.07936	eval-mlogloss:1.08151
[2]	train-mlogloss:1.06594	eval-mlogloss:1.06764
[3]	train-mlogloss:1.05586	eval-mlogloss:1.05648
[4]	train-mlogloss:1.04510	eval-mlogloss:1.04516
[5]	train-mlogloss:1.03235	eval-mlogloss:1.03177
[6]	train-mlogloss:1.02257	eval-mlogloss:1.02219
[7]	train-mlogloss:1.01494	eval-mlogloss:1.01501
[8]	train-mlogloss:1.00271	eval-mlogloss:1.00217
[9]	train-mlogloss:0.99339	eval-mlogloss:0.99305
[10]	train-mlogloss:0.98146	eval-mlogloss:0.98077
[11]	train-mlogloss:0.97108	eval-mlogloss:0.97018
[12]	train-mlogloss:0.96669	eval-mlogloss:0.96527
[13]	train-mlogloss:0.95540	eval-mlogloss:0.95312
[14]	train-mlogloss:0.95122	eval-mlogloss:0.94966
[15]	train-mlogloss:0.94451	eval-mlogloss:0.94310
[16]	train-mlogloss:0.93730	eval-mlogloss:0.93580
[17]	train-mlogloss:0.92886	eval-mlogloss:0.92756
[18]	train-mlogloss:0.92239	eval-mlogloss:0.92142
[19]	train-mlogloss:0.91603	eval-mlogloss:0.91529
[20]	train-mlogloss:0.90547	eval-mlogloss:0.90413
[21]	train-mlogloss:0.89801	eval-mlogloss:0.89674
[22]	train-mlogloss:0.89135	eval-mlogloss:0.89024
[23]	train-mlogloss:0.88126	eval-mlogloss:0.87962
[24]	train-mlogloss:0.87538	eval-mlogloss:0.87340
[25]	train-mlogloss:0.86792	eval-mlogloss:0.86508
[26]	train-mlogloss:0.85988	eval-mlogloss:0.85666
[27]	train-mlogloss:0.85737	eval-mlogloss:0.85466
[28]	train-mlogloss:0.85395	eval-mlogloss:0.85177
[29]	train-mlogloss:0.84644	eval-mlogloss:0.84353
[30]	train-mlogloss:0.83931	eval-mlogloss:0.83595
[31]	train-mlogloss:0.83679	eval-mlogloss:0.83429
[32]	train-mlogloss:0.83197	eval-mlogloss:0.82991
[33]	train-mlogloss:0.82758	eval-mlogloss:0.82548
[34]	train-mlogloss:0.81949	eval-mlogloss:0.81705
[35]	train-mlogloss:0.81477	eval-mlogloss:0.81190
[36]	train-mlogloss:0.81062	eval-mlogloss:0.80794
[37]	train-mlogloss:0.80442	eval-mlogloss:0.80159
[38]	train-mlogloss:0.79745	eval-mlogloss:0.79449
[39]	train-mlogloss:0.79216	eval-mlogloss:0.78903
[40]	train-mlogloss:0.78930	eval-mlogloss:0.78633
[41]	train-mlogloss:0.78308	eval-mlogloss:0.77934
[42]	train-mlogloss:0.78085	eval-mlogloss:0.77788
[43]	train-mlogloss:0.77477	eval-mlogloss:0.77150
[44]	train-mlogloss:0.76843	eval-mlogloss:0.76493
[45]	train-mlogloss:0.76478	eval-mlogloss:0.76090
[46]	train-mlogloss:0.75857	eval-mlogloss:0.75453
[47]	train-mlogloss:0.75397	eval-mlogloss:0.74985
[48]	train-mlogloss:0.74741	eval-mlogloss:0.74300
[49]	train-mlogloss:0.74087	eval-mlogloss:0.73622
[50]	train-mlogloss:0.73474	eval-mlogloss:0.72951
[51]	train-mlogloss:0.73100	eval-mlogloss:0.72591
[52]	train-mlogloss:0.72728	eval-mlogloss:0.72232
[53]	train-mlogloss:0.71977	eval-mlogloss:0.71407
[54]	train-mlogloss:0.71620	eval-mlogloss:0.71039
[55]	train-mlogloss:0.70870	eval-mlogloss:0.70260
[56]	train-mlogloss:0.70292	eval-mlogloss:0.69663
[57]	train-mlogloss:0.69574	eval-mlogloss:0.68874
[58]	train-mlogloss:0.69183	eval-mlogloss:0.68511
[59]	train-mlogloss:0.68952	eval-mlogloss:0.68267
[60]	train-mlogloss:0.68449	eval-mlogloss:0.67712
[61]	train-mlogloss:0.68012	eval-mlogloss:0.67239
[62]	train-mlogloss:0.67317	eval-mlogloss:0.66520
[63]	train-mlogloss:0.66937	eval-mlogloss:0.66163
[64]	train-mlogloss:0.66709	eval-mlogloss:0.65967
[65]	train-mlogloss:0.66325	eval-mlogloss:0.65577
[66]	train-mlogloss:0.65806	eval-mlogloss:0.65051
[67]	train-mlogloss:0.65388	eval-mlogloss:0.64634
[68]	train-mlogloss:0.65178	eval-mlogloss:0.64403
[69]	train-mlogloss:0.64526	eval-mlogloss:0.63705
[70]	train-mlogloss:0.64141	eval-mlogloss:0.63271
[71]	train-mlogloss:0.63503	eval-mlogloss:0.62588
[72]	train-mlogloss:0.63003	eval-mlogloss:0.62077
[73]	train-mlogloss:0.62638	eval-mlogloss:0.61683
[74]	train-mlogloss:0.62207	eval-mlogloss:0.61227
[75]	train-mlogloss:0.61679	eval-mlogloss:0.60657
[76]	train-mlogloss:0.61354	eval-mlogloss:0.60363
[77]	train-mlogloss:0.61090	eval-mlogloss:0.60122
[78]	train-mlogloss:0.60802	eval-mlogloss:0.59829
[79]	train-mlogloss:0.60540	eval-mlogloss:0.59593
[80]	train-mlogloss:0.60241	eval-mlogloss:0.59275
[81]	train-mlogloss:0.59789	eval-mlogloss:0.58804
[82]	train-mlogloss:0.59518	eval-mlogloss:0.58535
[83]	train-mlogloss:0.59126	eval-mlogloss:0.58103
[84]	train-mlogloss:0.58807	eval-mlogloss:0.57765
[85]	train-mlogloss:0.58392	eval-mlogloss:0.57333
[86]	train-mlogloss:0.57955	eval-mlogloss:0.56856
[87]	train-mlogloss:0.57533	eval-mlogloss:0.56391
[88]	train-mlogloss:0.57191	eval-mlogloss:0.56002
[89]	train-mlogloss:0.56755	eval-mlogloss:0.55559
[90]	train-mlogloss:0.56360	eval-mlogloss:0.55116
[91]	train-mlogloss:0.56053	eval-mlogloss:0.54801
[92]	train-mlogloss:0.55585	eval-mlogloss:0.54307
[93]	train-mlogloss:0.55412	eval-mlogloss:0.54153
[94]	train-mlogloss:0.54899	eval-mlogloss:0.53572
[95]	train-mlogloss:0.54454	eval-mlogloss:0.53074
[96]	train-mlogloss:0.53947	eval-mlogloss:0.52521
[97]	train-mlogloss:0.53686	eval-mlogloss:0.52258
[98]	train-mlogloss:0.53392	eval-mlogloss:0.51915
[99]	train-mlogloss:0.53294	eval-mlogloss:0.51850
[100]	train-mlogloss:0.52955	eval-mlogloss:0.51502
[101]	train-mlogloss:0.52663	eval-mlogloss:0.51171
[102]	train-mlogloss:0.52436	eval-mlogloss:0.50942
[103]	train-mlogloss:0.51952	eval-mlogloss:0.50414
[104]	train-mlogloss:0.51677	eval-mlogloss:0.50130
[105]	train-mlogloss:0.51423	eval-mlogloss:0.49874
[106]	train-mlogloss:0.51111	eval-mlogloss:0.49543
[107]	train-mlogloss:0.50653	eval-mlogloss:0.49032
[108]	train-mlogloss:0.50408	eval-mlogloss:0.48759
[109]	train-mlogloss:0.49956	eval-mlogloss:0.48255
[110]	train-mlogloss:0.49692	eval-mlogloss:0.47952
[111]	train-mlogloss:0.49332	eval-mlogloss:0.47558
[112]	train-mlogloss:0.49082	eval-mlogloss:0.47313
[113]	train-mlogloss:0.48639	eval-mlogloss:0.46814
[114]	train-mlogloss:0.48407	eval-mlogloss:0.46587
[115]	train-mlogloss:0.48110	eval-mlogloss:0.46270
[116]	train-mlogloss:0.47695	eval-mlogloss:0.45821
[117]	train-mlogloss:0.47366	eval-mlogloss:0.45457
[118]	train-mlogloss:0.47063	eval-mlogloss:0.45132
[119]	train-mlogloss:0.46837	eval-mlogloss:0.44888
[120]	train-mlogloss:0.46428	eval-mlogloss:0.44439
[121]	train-mlogloss:0.46110	eval-mlogloss:0.44090
[122]	train-mlogloss:0.45708	eval-mlogloss:0.43629
[123]	train-mlogloss:0.45357	eval-mlogloss:0.43243
[124]	train-mlogloss:0.45085	eval-mlogloss:0.42947
[125]	train-mlogloss:0.44809	eval-mlogloss:0.42634
[126]	train-mlogloss:0.44598	eval-mlogloss:0.42413
[127]	train-mlogloss:0.44399	eval-mlogloss:0.42199
[128]	train-mlogloss:0.44128	eval-mlogloss:0.41917
[129]	train-mlogloss:0.43945	eval-mlogloss:0.41714
[130]	train-mlogloss:0.43872	eval-mlogloss:0.41674
[131]	train-mlogloss:0.43498	eval-mlogloss:0.41239
[132]	train-mlogloss:0.43208	eval-mlogloss:0.40915
[133]	train-mlogloss:0.42969	eval-mlogloss:0.40645
[134]	train-mlogloss:0.42807	eval-mlogloss:0.40479
[135]	train-mlogloss:0.42535	eval-mlogloss:0.40157
[136]	train-mlogloss:0.42313	eval-mlogloss:0.39907
[137]	train-mlogloss:0.41961	eval-mlogloss:0.39537
[138]	train-mlogloss:0.41706	eval-mlogloss:0.39269
[139]	train-mlogloss:0.41549	eval-mlogloss:0.39130
[140]	train-mlogloss:0.41282	eval-mlogloss:0.38830
[141]	train-mlogloss:0.41033	eval-mlogloss:0.38561
[142]	train-mlogloss:0.40761	eval-mlogloss:0.38275
[143]	train-mlogloss:0.40419	eval-mlogloss:0.37909
[144]	train-mlogloss:0.40144	eval-mlogloss:0.37608
[145]	train-mlogloss:0.39934	eval-mlogloss:0.37370
[146]	train-mlogloss:0.39689	eval-mlogloss:0.37091
[147]	train-mlogloss:0.39471	eval-mlogloss:0.36856
[148]	train-mlogloss:0.39229	eval-mlogloss:0.36595
[149]	train-mlogloss:0.39147	eval-mlogloss:0.36515
[150]	train-mlogloss:0.38831	eval-mlogloss:0.36164
[151]	train-mlogloss:0.38518	eval-mlogloss:0.35806
[152]	train-mlogloss:0.38368	eval-mlogloss:0.35646
[153]	train-mlogloss:0.38159	eval-mlogloss:0.35429
[154]	train-mlogloss:0.37845	eval-mlogloss:0.35093
[155]	train-mlogloss:0.37609	eval-mlogloss:0.34831
[156]	train-mlogloss:0.37382	eval-mlogloss:0.34578
[157]	train-mlogloss:0.37239	eval-mlogloss:0.34422
[158]	train-mlogloss:0.36987	eval-mlogloss:0.34140
[159]	train-mlogloss:0.36847	eval-mlogloss:0.33989
[160]	train-mlogloss:0.36607	eval-mlogloss:0.33716
[161]	train-mlogloss:0.36320	eval-mlogloss:0.33407
[162]	train-mlogloss:0.36167	eval-mlogloss:0.33236
[163]	train-mlogloss:0.36024	eval-mlogloss:0.33083
[164]	train-mlogloss:0.35963	eval-mlogloss:0.33037
[165]	train-mlogloss:0.35835	eval-mlogloss:0.32883
[166]	train-mlogloss:0.35561	eval-mlogloss:0.32573
[167]	train-mlogloss:0.35297	eval-mlogloss:0.32286
[168]	train-mlogloss:0.35107	eval-mlogloss:0.32072
[169]	train-mlogloss:0.34999	eval-mlogloss:0.31967
[170]	train-mlogloss:0.34957	eval-mlogloss:0.31944
[171]	train-mlogloss:0.34777	eval-mlogloss:0.31762
[172]	train-mlogloss:0.34712	eval-mlogloss:0.31706
[173]	train-mlogloss:0.34622	eval-mlogloss:0.31608
[174]	train-mlogloss:0.34479	eval-mlogloss:0.31438
[175]	train-mlogloss:0.34344	eval-mlogloss:0.31299
[176]	train-mlogloss:0.34122	eval-mlogloss:0.31049
[177]	train-mlogloss:0.34036	eval-mlogloss:0.30956
[178]	train-mlogloss:0.33854	eval-mlogloss:0.30759
[179]	train-mlogloss:0.33764	eval-mlogloss:0.30651
[180]	train-mlogloss:0.33595	eval-mlogloss:0.30455
[181]	train-mlogloss:0.33416	eval-mlogloss:0.30263
[182]	train-mlogloss:0.33296	eval-mlogloss:0.30134
[183]	train-mlogloss:0.33234	eval-mlogloss:0.30081
[184]	train-mlogloss:0.33057	eval-mlogloss:0.29891
[185]	train-mlogloss:0.32881	eval-mlogloss:0.29707
[186]	train-mlogloss:0.32706	eval-mlogloss:0.29518
[187]	train-mlogloss:0.32537	eval-mlogloss:0.29326
[188]	train-mlogloss:0.32348	eval-mlogloss:0.29099
[189]	train-mlogloss:0.32107	eval-mlogloss:0.28841
[190]	train-mlogloss:0.31993	eval-mlogloss:0.28719
[191]	train-mlogloss:0.31839	eval-mlogloss:0.28535
[192]	train-mlogloss:0.31710	eval-mlogloss:0.28397
[193]	train-mlogloss:0.31585	eval-mlogloss:0.28246
[194]	train-mlogloss:0.31432	eval-mlogloss:0.28069
[195]	train-mlogloss:0.31216	eval-mlogloss:0.27832
[196]	train-mlogloss:0.31072	eval-mlogloss:0.27685
[197]	train-mlogloss:0.30862	eval-mlogloss:0.27451
[198]	train-mlogloss:0.30762	eval-mlogloss:0.27350
[199]	train-mlogloss:0.30662	eval-mlogloss:0.27234
[200]	train-mlogloss:0.30512	eval-mlogloss:0.27073
[201]	train-mlogloss:0.30415	eval-mlogloss:0.26976
[202]	train-mlogloss:0.30338	eval-mlogloss:0.26899
[203]	train-mlogloss:0.30189	eval-mlogloss:0.26737
[204]	train-mlogloss:0.30094	eval-mlogloss:0.26640
[205]	train-mlogloss:0.30004	eval-mlogloss:0.26533
[206]	train-mlogloss:0.29890	eval-mlogloss:0.26409
[207]	train-mlogloss:0.29775	eval-mlogloss:0.26269
[208]	train-mlogloss:0.29629	eval-mlogloss:0.26113
[209]	train-mlogloss:0.29446	eval-mlogloss:0.25891
[210]	train-mlogloss:0.29397	eval-mlogloss:0.25849
[211]	train-mlogloss:0.29319	eval-mlogloss:0.25777
[212]	train-mlogloss:0.29177	eval-mlogloss:0.25625
[213]	train-mlogloss:0.29016	eval-mlogloss:0.25447
[214]	train-mlogloss:0.28837	eval-mlogloss:0.25237
[215]	train-mlogloss:0.28668	eval-mlogloss:0.25025
[216]	train-mlogloss:0.28601	eval-mlogloss:0.24952
[217]	train-mlogloss:0.28429	eval-mlogloss:0.24735
[218]	train-mlogloss:0.28384	eval-mlogloss:0.24696
[219]	train-mlogloss:0.28201	eval-mlogloss:0.24494
[220]	train-mlogloss:0.28116	eval-mlogloss:0.24407
[221]	train-mlogloss:0.28031	eval-mlogloss:0.24311
[222]	train-mlogloss:0.27949	eval-mlogloss:0.24231
[223]	train-mlogloss:0.27867	eval-mlogloss:0.24143
[224]	train-mlogloss:0.27738	eval-mlogloss:0.24010
[225]	train-mlogloss:0.27687	eval-mlogloss:0.23952
[226]	train-mlogloss:0.27573	eval-mlogloss:0.23810
[227]	train-mlogloss:0.27509	eval-mlogloss:0.23755
[228]	train-mlogloss:0.27430	eval-mlogloss:0.23672
[229]	train-mlogloss:0.27323	eval-mlogloss:0.23555
[230]	train-mlogloss:0.27287	eval-mlogloss:0.23511
[231]	train-mlogloss:0.27173	eval-mlogloss:0.23370
[232]	train-mlogloss:0.27152	eval-mlogloss:0.23367
[233]	train-mlogloss:0.27055	eval-mlogloss:0.23246
[234]	train-mlogloss:0.26900	eval-mlogloss:0.23051
[235]	train-mlogloss:0.26775	eval-mlogloss:0.22885
[236]	train-mlogloss:0.26702	eval-mlogloss:0.22800
[237]	train-mlogloss:0.26592	eval-mlogloss:0.22677
[238]	train-mlogloss:0.26487	eval-mlogloss:0.22550
[239]	train-mlogloss:0.26388	eval-mlogloss:0.22439
[240]	train-mlogloss:0.26243	eval-mlogloss:0.22260
[241]	train-mlogloss:0.26176	eval-mlogloss:0.22194
[242]	train-mlogloss:0.26071	eval-mlogloss:0.22072
[243]	train-mlogloss:0.26006	eval-mlogloss:0.22008
[244]	train-mlogloss:0.25944	eval-mlogloss:0.21954
[245]	train-mlogloss:0.25833	eval-mlogloss:0.21820
[246]	train-mlogloss:0.25774	eval-mlogloss:0.21749
[247]	train-mlogloss:0.25750	eval-mlogloss:0.21722
[248]	train-mlogloss:0.25736	eval-mlogloss:0.21716
[249]	train-mlogloss:0.25619	eval-mlogloss:0.21560
[250]	train-mlogloss:0.25512	eval-mlogloss:0.21432
[251]	train-mlogloss:0.25442	eval-mlogloss:0.21350
[252]	train-mlogloss:0.25376	eval-mlogloss:0.21274
[253]	train-mlogloss:0.25317	eval-mlogloss:0.21205
[254]	train-mlogloss:0.25231	eval-mlogloss:0.21099
[255]	train-mlogloss:0.25180	eval-mlogloss:0.21064
[256]	train-mlogloss:0.25103	eval-mlogloss:0.20971
[257]	train-mlogloss:0.25011	eval-mlogloss:0.20863
[258]	train-mlogloss:0.24939	eval-mlogloss:0.20773
[259]	train-mlogloss:0.24908	eval-mlogloss:0.20749
[260]	train-mlogloss:0.24877	eval-mlogloss:0.20724
[261]	train-mlogloss:0.24785	eval-mlogloss:0.20609
[262]	train-mlogloss:0.24687	eval-mlogloss:0.20508
[263]	train-mlogloss:0.24592	eval-mlogloss:0.20395
[264]	train-mlogloss:0.24572	eval-mlogloss:0.20388
[265]	train-mlogloss:0.24510	eval-mlogloss:0.20318
[266]	train-mlogloss:0.24408	eval-mlogloss:0.20214
[267]	train-mlogloss:0.24347	eval-mlogloss:0.20146
[268]	train-mlogloss:0.24289	eval-mlogloss:0.20077
[269]	train-mlogloss:0.24190	eval-mlogloss:0.19944
[270]	train-mlogloss:0.24093	eval-mlogloss:0.19831
[271]	train-mlogloss:0.24013	eval-mlogloss:0.19754
[272]	train-mlogloss:0.23889	eval-mlogloss:0.19608
[273]	train-mlogloss:0.23831	eval-mlogloss:0.19545
[274]	train-mlogloss:0.23773	eval-mlogloss:0.19479
[275]	train-mlogloss:0.23647	eval-mlogloss:0.19329
[276]	train-mlogloss:0.23588	eval-mlogloss:0.19252
[277]	train-mlogloss:0.23511	eval-mlogloss:0.19166
[278]	train-mlogloss:0.23432	eval-mlogloss:0.19071
[279]	train-mlogloss:0.23338	eval-mlogloss:0.18971
[280]	train-mlogloss:0.23256	eval-mlogloss:0.18877
[281]	train-mlogloss:0.23167	eval-mlogloss:0.18783
[282]	train-mlogloss:0.23075	eval-mlogloss:0.18679
[283]	train-mlogloss:0.23053	eval-mlogloss:0.18654
[284]	train-mlogloss:0.22951	eval-mlogloss:0.18533
[285]	train-mlogloss:0.22901	eval-mlogloss:0.18490
[286]	train-mlogloss:0.22801	eval-mlogloss:0.18378
[287]	train-mlogloss:0.22692	eval-mlogloss:0.18238
[288]	train-mlogloss:0.22640	eval-mlogloss:0.18181
[289]	train-mlogloss:0.22565	eval-mlogloss:0.18100
[290]	train-mlogloss:0.22500	eval-mlogloss:0.18025
[291]	train-mlogloss:0.22416	eval-mlogloss:0.17935
[292]	train-mlogloss:0.22389	eval-mlogloss:0.17917
[293]	train-mlogloss:0.22351	eval-mlogloss:0.17886
[294]	train-mlogloss:0.22245	eval-mlogloss:0.17773
[295]	train-mlogloss:0.22197	eval-mlogloss:0.17712
[296]	train-mlogloss:0.22148	eval-mlogloss:0.17659
[297]	train-mlogloss:0.22054	eval-mlogloss:0.17554
[298]	train-mlogloss:0.22015	eval-mlogloss:0.17504
[299]	train-mlogloss:0.21926	eval-mlogloss:0.17384

[I 2026-02-27 06:06:54,528] Trial 42 finished with value: 1.0 and parameters: {'lambda': 0.03371510100639687, 'alpha': 0.22951224079199792, 'eta': 0.010619005504206906, 'gamma': 0.3240491916191798, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.9432251235563979, 'colsample_bytree': 0.4471436093085899}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.08180	eval-mlogloss:1.08538
[1]	train-mlogloss:1.04097	eval-mlogloss:1.04270
[2]	train-mlogloss:1.00276	eval-mlogloss:1.00299
[3]	train-mlogloss:0.97501	eval-mlogloss:0.97214
[4]	train-mlogloss:0.94566	eval-mlogloss:0.94053
[5]	train-mlogloss:0.91244	eval-mlogloss:0.90534
[6]	train-mlogloss:0.88785	eval-mlogloss:0.88016
[7]	train-mlogloss:0.86983	eval-mlogloss:0.86293

[I 2026-02-27 06:06:54,587] Trial 43 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.02308	eval-mlogloss:1.01828
[1]	train-mlogloss:0.85260	eval-mlogloss:0.84049

[I 2026-02-27 06:06:54,628] Trial 44 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.06287	eval-mlogloss:1.06629
[1]	train-mlogloss:1.01203	eval-mlogloss:1.01324
[2]	train-mlogloss:0.96447	eval-mlogloss:0.96433
[3]	train-mlogloss:0.91946	eval-mlogloss:0.91825
[4]	train-mlogloss:0.87790	eval-mlogloss:0.87576
[5]	train-mlogloss:0.83869	eval-mlogloss:0.83369
[6]	train-mlogloss:0.80279	eval-mlogloss:0.79684
[7]	train-mlogloss:0.76910	eval-mlogloss:0.76218

[I 2026-02-27 06:06:54,693] Trial 45 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.07855	eval-mlogloss:1.08124
[1]	train-mlogloss:1.05220	eval-mlogloss:1.05370
[2]	train-mlogloss:1.02694	eval-mlogloss:1.02749
[3]	train-mlogloss:1.00215	eval-mlogloss:1.00205
[4]	train-mlogloss:0.97833	eval-mlogloss:0.97772
[5]	train-mlogloss:0.95530	eval-mlogloss:0.95345
[6]	train-mlogloss:0.93299	eval-mlogloss:0.93047
[7]	train-mlogloss:0.91143	eval-mlogloss:0.90825

[I 2026-02-27 06:06:54,827] Trial 46 pruned. Trial was pruned at iteration 8.

[0]	train-mlogloss:1.06402	eval-mlogloss:1.06699
[1]	train-mlogloss:0.98607	eval-mlogloss:0.98578

[I 2026-02-27 06:06:54,968] Trial 47 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.04670	eval-mlogloss:1.04690
[1]	train-mlogloss:0.98347	eval-mlogloss:0.98080

[I 2026-02-27 06:06:55,108] Trial 48 pruned. Trial was pruned at iteration 2.

[0]	train-mlogloss:1.03245	eval-mlogloss:1.03999
[1]	train-mlogloss:0.88457	eval-mlogloss:0.88437

[I 2026-02-27 06:06:55,138] Trial 49 pruned. Trial was pruned at iteration 2.

Best trial: {'lambda': 0.39807941021872445, 'alpha': 0.7194273512369619, 'eta': 0.04346150465161059, 'gamma': 0.018493726865413496, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.9565429480675249, 'colsample_bytree': 0.4240353787786787}
Best accuracy: 1.0

In [72]:
! pip install optuna-integration[xgboost]

Requirement already satisfied: optuna-integration[xgboost] in /usr/local/lib/python3.12/dist-packages (4.7.0)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (4.7.0)
Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (from optuna-integration[xgboost]) (3.2.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (1.18.4)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (26.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (2.0.47)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna->optuna-integration[xgboost]) (6.0.3)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (2.27.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost->optuna-integration[xgboost]) (1.16.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.3.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (3.0.3)

In [73]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()